/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kisti.osp.icecap.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the DataEntryProvenance service. Represents a row in the &quot;icecap_DataEntryProvenance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.kisti.osp.icecap.model.impl.DataEntryProvenanceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.kisti.osp.icecap.model.impl.DataEntryProvenanceImpl}.
 * </p>
 *
 * @author Young-K. Suh and Jerry H. Seo
 * @see DataEntryProvenance
 * @see com.kisti.osp.icecap.model.impl.DataEntryProvenanceImpl
 * @see com.kisti.osp.icecap.model.impl.DataEntryProvenanceModelImpl
 * @generated
 */
public interface DataEntryProvenanceModel extends BaseModel<DataEntryProvenance> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a data entry provenance model instance should use the {@link DataEntryProvenance} interface instead.
	 */

	/**
	 * Returns the primary key of this data entry provenance.
	 *
	 * @return the primary key of this data entry provenance
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this data entry provenance.
	 *
	 * @param primaryKey the primary key of this data entry provenance
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the entry ID of this data entry provenance.
	 *
	 * @return the entry ID of this data entry provenance
	 */
	public long getEntryId();

	/**
	 * Sets the entry ID of this data entry provenance.
	 *
	 * @param entryId the entry ID of this data entry provenance
	 */
	public void setEntryId(long entryId);

	/**
	 * Returns the input data of this data entry provenance.
	 *
	 * @return the input data of this data entry provenance
	 */
	@AutoEscape
	public String getInputData();

	/**
	 * Sets the input data of this data entry provenance.
	 *
	 * @param inputData the input data of this data entry provenance
	 */
	public void setInputData(String inputData);

	/**
	 * Returns the p r o v structure of this data entry provenance.
	 *
	 * @return the p r o v structure of this data entry provenance
	 */
	@AutoEscape
	public String getPROVStructure();

	/**
	 * Sets the p r o v structure of this data entry provenance.
	 *
	 * @param PROVStructure the p r o v structure of this data entry provenance
	 */
	public void setPROVStructure(String PROVStructure);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.kisti.osp.icecap.model.DataEntryProvenance dataEntryProvenance);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.kisti.osp.icecap.model.DataEntryProvenance> toCacheModel();

	@Override
	public com.kisti.osp.icecap.model.DataEntryProvenance toEscapedModel();

	@Override
	public com.kisti.osp.icecap.model.DataEntryProvenance toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}