/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kisti.osp.icecap.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the DataTypeStructure service. Represents a row in the &quot;icecap_DataTypeStructure&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.kisti.osp.icecap.model.impl.DataTypeStructureModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.kisti.osp.icecap.model.impl.DataTypeStructureImpl}.
 * </p>
 *
 * @author Young-K. Suh and Jerry H. Seo
 * @see DataTypeStructure
 * @see com.kisti.osp.icecap.model.impl.DataTypeStructureImpl
 * @see com.kisti.osp.icecap.model.impl.DataTypeStructureModelImpl
 * @generated
 */
public interface DataTypeStructureModel extends BaseModel<DataTypeStructure> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a data type structure model instance should use the {@link DataTypeStructure} interface instead.
	 */

	/**
	 * Returns the primary key of this data type structure.
	 *
	 * @return the primary key of this data type structure
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this data type structure.
	 *
	 * @param primaryKey the primary key of this data type structure
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the type ID of this data type structure.
	 *
	 * @return the type ID of this data type structure
	 */
	public long getTypeId();

	/**
	 * Sets the type ID of this data type structure.
	 *
	 * @param typeId the type ID of this data type structure
	 */
	public void setTypeId(long typeId);

	/**
	 * Returns the structure of this data type structure.
	 *
	 * @return the structure of this data type structure
	 */
	@AutoEscape
	public String getStructure();

	/**
	 * Sets the structure of this data type structure.
	 *
	 * @param structure the structure of this data type structure
	 */
	public void setStructure(String structure);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.kisti.osp.icecap.model.DataTypeStructure dataTypeStructure);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.kisti.osp.icecap.model.DataTypeStructure> toCacheModel();

	@Override
	public com.kisti.osp.icecap.model.DataTypeStructure toEscapedModel();

	@Override
	public com.kisti.osp.icecap.model.DataTypeStructure toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}