/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kisti.osp.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FileManagement service. Represents a row in the &quot;OSP_FileManagement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.kisti.osp.model.impl.FileManagementModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.kisti.osp.model.impl.FileManagementImpl}.
 * </p>
 *
 * @author Jerry h. Seo
 * @see FileManagement
 * @see com.kisti.osp.model.impl.FileManagementImpl
 * @see com.kisti.osp.model.impl.FileManagementModelImpl
 * @generated
 */
public interface FileManagementModel extends BaseModel<FileManagement> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a file management model instance should use the {@link FileManagement} interface instead.
	 */

	/**
	 * Returns the primary key of this file management.
	 *
	 * @return the primary key of this file management
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this file management.
	 *
	 * @param primaryKey the primary key of this file management
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user ID of this file management.
	 *
	 * @return the user ID of this file management
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this file management.
	 *
	 * @param userId the user ID of this file management
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this file management.
	 *
	 * @return the user uuid of this file management
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this file management.
	 *
	 * @param userUuid the user uuid of this file management
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the assigned of this file management.
	 *
	 * @return the assigned of this file management
	 */
	public int getAssigned();

	/**
	 * Sets the assigned of this file management.
	 *
	 * @param assigned the assigned of this file management
	 */
	public void setAssigned(int assigned);

	/**
	 * Returns the used of this file management.
	 *
	 * @return the used of this file management
	 */
	public int getUsed();

	/**
	 * Sets the used of this file management.
	 *
	 * @param used the used of this file management
	 */
	public void setUsed(int used);

	/**
	 * Returns the last modified of this file management.
	 *
	 * @return the last modified of this file management
	 */
	public Date getLastModified();

	/**
	 * Sets the last modified of this file management.
	 *
	 * @param lastModified the last modified of this file management
	 */
	public void setLastModified(Date lastModified);

	/**
	 * Returns the status of this file management.
	 *
	 * @return the status of this file management
	 */
	public int getStatus();

	/**
	 * Sets the status of this file management.
	 *
	 * @param status the status of this file management
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.kisti.osp.model.FileManagement fileManagement);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.kisti.osp.model.FileManagement> toCacheModel();

	@Override
	public com.kisti.osp.model.FileManagement toEscapedModel();

	@Override
	public com.kisti.osp.model.FileManagement toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}