/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.kisti.edison.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the WorkflowSimulation service. Represents a row in the &quot;EDWF_WorkflowSimulation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.kisti.edison.model.impl.WorkflowSimulationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.kisti.edison.model.impl.WorkflowSimulationImpl}.
 * </p>
 *
 * @author EDISON
 * @see WorkflowSimulation
 * @see org.kisti.edison.model.impl.WorkflowSimulationImpl
 * @see org.kisti.edison.model.impl.WorkflowSimulationModelImpl
 * @generated
 */
public interface WorkflowSimulationModel extends BaseModel<WorkflowSimulation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a workflow simulation model instance should use the {@link WorkflowSimulation} interface instead.
	 */

	/**
	 * Returns the primary key of this workflow simulation.
	 *
	 * @return the primary key of this workflow simulation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this workflow simulation.
	 *
	 * @param primaryKey the primary key of this workflow simulation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the simulation ID of this workflow simulation.
	 *
	 * @return the simulation ID of this workflow simulation
	 */
	public long getSimulationId();

	/**
	 * Sets the simulation ID of this workflow simulation.
	 *
	 * @param simulationId the simulation ID of this workflow simulation
	 */
	public void setSimulationId(long simulationId);

	/**
	 * Returns the user ID of this workflow simulation.
	 *
	 * @return the user ID of this workflow simulation
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this workflow simulation.
	 *
	 * @param userId the user ID of this workflow simulation
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this workflow simulation.
	 *
	 * @return the user uuid of this workflow simulation
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this workflow simulation.
	 *
	 * @param userUuid the user uuid of this workflow simulation
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this workflow simulation.
	 *
	 * @return the create date of this workflow simulation
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this workflow simulation.
	 *
	 * @param createDate the create date of this workflow simulation
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this workflow simulation.
	 *
	 * @return the modified date of this workflow simulation
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this workflow simulation.
	 *
	 * @param modifiedDate the modified date of this workflow simulation
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the class ID of this workflow simulation.
	 *
	 * @return the class ID of this workflow simulation
	 */
	public long getClassId();

	/**
	 * Sets the class ID of this workflow simulation.
	 *
	 * @param classId the class ID of this workflow simulation
	 */
	public void setClassId(long classId);

	/**
	 * Returns the custom ID of this workflow simulation.
	 *
	 * @return the custom ID of this workflow simulation
	 */
	public long getCustomId();

	/**
	 * Sets the custom ID of this workflow simulation.
	 *
	 * @param customId the custom ID of this workflow simulation
	 */
	public void setCustomId(long customId);

	/**
	 * Returns the title of this workflow simulation.
	 *
	 * @return the title of this workflow simulation
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this workflow simulation.
	 *
	 * @param title the title of this workflow simulation
	 */
	public void setTitle(String title);

	/**
	 * Returns the test yn of this workflow simulation.
	 *
	 * @return the test yn of this workflow simulation
	 */
	public boolean getTestYn();

	/**
	 * Returns <code>true</code> if this workflow simulation is test yn.
	 *
	 * @return <code>true</code> if this workflow simulation is test yn; <code>false</code> otherwise
	 */
	public boolean isTestYn();

	/**
	 * Sets whether this workflow simulation is test yn.
	 *
	 * @param testYn the test yn of this workflow simulation
	 */
	public void setTestYn(boolean testYn);

	/**
	 * Returns the workflow ID of this workflow simulation.
	 *
	 * @return the workflow ID of this workflow simulation
	 */
	public long getWorkflowId();

	/**
	 * Sets the workflow ID of this workflow simulation.
	 *
	 * @param workflowId the workflow ID of this workflow simulation
	 */
	public void setWorkflowId(long workflowId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.kisti.edison.model.WorkflowSimulation workflowSimulation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.kisti.edison.model.WorkflowSimulation> toCacheModel();

	@Override
	public org.kisti.edison.model.WorkflowSimulation toEscapedModel();

	@Override
	public org.kisti.edison.model.WorkflowSimulation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}