/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.kisti.edison.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the WorkflowSimulationJob service. Represents a row in the &quot;EDWF_WorkflowSimulationJob&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.kisti.edison.model.impl.WorkflowSimulationJobModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.kisti.edison.model.impl.WorkflowSimulationJobImpl}.
 * </p>
 *
 * @author EDISON
 * @see WorkflowSimulationJob
 * @see org.kisti.edison.model.impl.WorkflowSimulationJobImpl
 * @see org.kisti.edison.model.impl.WorkflowSimulationJobModelImpl
 * @generated
 */
public interface WorkflowSimulationJobModel extends BaseModel<WorkflowSimulationJob> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a workflow simulation job model instance should use the {@link WorkflowSimulationJob} interface instead.
	 */

	/**
	 * Returns the primary key of this workflow simulation job.
	 *
	 * @return the primary key of this workflow simulation job
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this workflow simulation job.
	 *
	 * @param primaryKey the primary key of this workflow simulation job
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the simulation job ID of this workflow simulation job.
	 *
	 * @return the simulation job ID of this workflow simulation job
	 */
	public long getSimulationJobId();

	/**
	 * Sets the simulation job ID of this workflow simulation job.
	 *
	 * @param simulationJobId the simulation job ID of this workflow simulation job
	 */
	public void setSimulationJobId(long simulationJobId);

	/**
	 * Returns the simulation ID of this workflow simulation job.
	 *
	 * @return the simulation ID of this workflow simulation job
	 */
	public long getSimulationId();

	/**
	 * Sets the simulation ID of this workflow simulation job.
	 *
	 * @param simulationId the simulation ID of this workflow simulation job
	 */
	public void setSimulationId(long simulationId);

	/**
	 * Returns the group ID of this workflow simulation job.
	 *
	 * @return the group ID of this workflow simulation job
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this workflow simulation job.
	 *
	 * @param groupId the group ID of this workflow simulation job
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this workflow simulation job.
	 *
	 * @return the user ID of this workflow simulation job
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this workflow simulation job.
	 *
	 * @param userId the user ID of this workflow simulation job
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this workflow simulation job.
	 *
	 * @return the user uuid of this workflow simulation job
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this workflow simulation job.
	 *
	 * @param userUuid the user uuid of this workflow simulation job
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this workflow simulation job.
	 *
	 * @return the create date of this workflow simulation job
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this workflow simulation job.
	 *
	 * @param createDate the create date of this workflow simulation job
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this workflow simulation job.
	 *
	 * @return the modified date of this workflow simulation job
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this workflow simulation job.
	 *
	 * @param modifiedDate the modified date of this workflow simulation job
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this workflow simulation job.
	 *
	 * @return the title of this workflow simulation job
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this workflow simulation job.
	 *
	 * @param title the title of this workflow simulation job
	 */
	public void setTitle(String title);

	/**
	 * Returns the status of this workflow simulation job.
	 *
	 * @return the status of this workflow simulation job
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this workflow simulation job.
	 *
	 * @param status the status of this workflow simulation job
	 */
	public void setStatus(String status);

	/**
	 * Returns the status response of this workflow simulation job.
	 *
	 * @return the status response of this workflow simulation job
	 */
	@AutoEscape
	public String getStatusResponse();

	/**
	 * Sets the status response of this workflow simulation job.
	 *
	 * @param statusResponse the status response of this workflow simulation job
	 */
	public void setStatusResponse(String statusResponse);

	/**
	 * Returns the start time of this workflow simulation job.
	 *
	 * @return the start time of this workflow simulation job
	 */
	public Date getStartTime();

	/**
	 * Sets the start time of this workflow simulation job.
	 *
	 * @param startTime the start time of this workflow simulation job
	 */
	public void setStartTime(Date startTime);

	/**
	 * Returns the end time of this workflow simulation job.
	 *
	 * @return the end time of this workflow simulation job
	 */
	public Date getEndTime();

	/**
	 * Sets the end time of this workflow simulation job.
	 *
	 * @param endTime the end time of this workflow simulation job
	 */
	public void setEndTime(Date endTime);

	/**
	 * Returns the workflow ID of this workflow simulation job.
	 *
	 * @return the workflow ID of this workflow simulation job
	 */
	public long getWorkflowId();

	/**
	 * Sets the workflow ID of this workflow simulation job.
	 *
	 * @param workflowId the workflow ID of this workflow simulation job
	 */
	public void setWorkflowId(long workflowId);

	/**
	 * Returns the workflow u u i d of this workflow simulation job.
	 *
	 * @return the workflow u u i d of this workflow simulation job
	 */
	@AutoEscape
	public String getWorkflowUUID();

	/**
	 * Sets the workflow u u i d of this workflow simulation job.
	 *
	 * @param workflowUUID the workflow u u i d of this workflow simulation job
	 */
	public void setWorkflowUUID(String workflowUUID);

	/**
	 * Returns the reuse workflow u u i d of this workflow simulation job.
	 *
	 * @return the reuse workflow u u i d of this workflow simulation job
	 */
	@AutoEscape
	public String getReuseWorkflowUUID();

	/**
	 * Sets the reuse workflow u u i d of this workflow simulation job.
	 *
	 * @param reuseWorkflowUUID the reuse workflow u u i d of this workflow simulation job
	 */
	public void setReuseWorkflowUUID(String reuseWorkflowUUID);

	/**
	 * Returns the screen logic of this workflow simulation job.
	 *
	 * @return the screen logic of this workflow simulation job
	 */
	@AutoEscape
	public String getScreenLogic();

	/**
	 * Sets the screen logic of this workflow simulation job.
	 *
	 * @param screenLogic the screen logic of this workflow simulation job
	 */
	public void setScreenLogic(String screenLogic);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.kisti.edison.model.WorkflowSimulationJob workflowSimulationJob);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.kisti.edison.model.WorkflowSimulationJob> toCacheModel();

	@Override
	public org.kisti.edison.model.WorkflowSimulationJob toEscapedModel();

	@Override
	public org.kisti.edison.model.WorkflowSimulationJob toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}