/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.kisti.edison.virtuallaboratory.model;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the ClassNote service. Represents a row in the &quot;EDVIR_ClassNote&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.kisti.edison.virtuallaboratory.model.impl.ClassNoteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.kisti.edison.virtuallaboratory.model.impl.ClassNoteImpl}.
 * </p>
 *
 * @author EDISON
 * @see ClassNote
 * @see org.kisti.edison.virtuallaboratory.model.impl.ClassNoteImpl
 * @see org.kisti.edison.virtuallaboratory.model.impl.ClassNoteModelImpl
 * @generated
 */
public interface ClassNoteModel extends BaseModel<ClassNote> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a class note model instance should use the {@link ClassNote} interface instead.
	 */

	/**
	 * Returns the primary key of this class note.
	 *
	 * @return the primary key of this class note
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this class note.
	 *
	 * @param primaryKey the primary key of this class note
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the class note seq of this class note.
	 *
	 * @return the class note seq of this class note
	 */
	public long getClassNoteSeq();

	/**
	 * Sets the class note seq of this class note.
	 *
	 * @param classNoteSeq the class note seq of this class note
	 */
	public void setClassNoteSeq(long classNoteSeq);

	/**
	 * Returns the class ID of this class note.
	 *
	 * @return the class ID of this class note
	 */
	public long getClassId();

	/**
	 * Sets the class ID of this class note.
	 *
	 * @param classId the class ID of this class note
	 */
	public void setClassId(long classId);

	/**
	 * Returns the content seq of this class note.
	 *
	 * @return the content seq of this class note
	 */
	public long getContentSeq();

	/**
	 * Sets the content seq of this class note.
	 *
	 * @param contentSeq the content seq of this class note
	 */
	public void setContentSeq(long contentSeq);

	/**
	 * Returns the is content of this class note.
	 *
	 * @return the is content of this class note
	 */
	@AutoEscape
	public String getIsContent();

	/**
	 * Sets the is content of this class note.
	 *
	 * @param isContent the is content of this class note
	 */
	public void setIsContent(String isContent);

	/**
	 * Returns the file entry ID of this class note.
	 *
	 * @return the file entry ID of this class note
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this class note.
	 *
	 * @param fileEntryId the file entry ID of this class note
	 */
	public void setFileEntryId(long fileEntryId);

	/**
	 * Returns the description of this class note.
	 *
	 * @return the description of this class note
	 */
	public String getDescription();

	/**
	 * Returns the localized description of this class note in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized description of this class note
	 */
	@AutoEscape
	public String getDescription(Locale locale);

	/**
	 * Returns the localized description of this class note in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this class note. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDescription(Locale locale, boolean useDefault);

	/**
	 * Returns the localized description of this class note in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized description of this class note
	 */
	@AutoEscape
	public String getDescription(String languageId);

	/**
	 * Returns the localized description of this class note in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this class note
	 */
	@AutoEscape
	public String getDescription(String languageId, boolean useDefault);

	@AutoEscape
	public String getDescriptionCurrentLanguageId();

	@AutoEscape
	public String getDescriptionCurrentValue();

	/**
	 * Returns a map of the locales and localized descriptions of this class note.
	 *
	 * @return the locales and localized descriptions of this class note
	 */
	public Map<Locale, String> getDescriptionMap();

	/**
	 * Sets the description of this class note.
	 *
	 * @param description the description of this class note
	 */
	public void setDescription(String description);

	/**
	 * Sets the localized description of this class note in the language.
	 *
	 * @param description the localized description of this class note
	 * @param locale the locale of the language
	 */
	public void setDescription(String description, Locale locale);

	/**
	 * Sets the localized description of this class note in the language, and sets the default locale.
	 *
	 * @param description the localized description of this class note
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDescription(String description, Locale locale,
		Locale defaultLocale);

	public void setDescriptionCurrentLanguageId(String languageId);

	/**
	 * Sets the localized descriptions of this class note from the map of locales and localized descriptions.
	 *
	 * @param descriptionMap the locales and localized descriptions of this class note
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap);

	/**
	 * Sets the localized descriptions of this class note from the map of locales and localized descriptions, and sets the default locale.
	 *
	 * @param descriptionMap the locales and localized descriptions of this class note
	 * @param defaultLocale the default locale
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap,
		Locale defaultLocale);

	/**
	 * Returns the insert date of this class note.
	 *
	 * @return the insert date of this class note
	 */
	public Date getInsertDate();

	/**
	 * Sets the insert date of this class note.
	 *
	 * @param insertDate the insert date of this class note
	 */
	public void setInsertDate(Date insertDate);

	/**
	 * Returns the update date of this class note.
	 *
	 * @return the update date of this class note
	 */
	public Date getUpdateDate();

	/**
	 * Sets the update date of this class note.
	 *
	 * @param updateDate the update date of this class note
	 */
	public void setUpdateDate(Date updateDate);

	/**
	 * Returns the insert ID of this class note.
	 *
	 * @return the insert ID of this class note
	 */
	public long getInsertId();

	/**
	 * Sets the insert ID of this class note.
	 *
	 * @param insertId the insert ID of this class note
	 */
	public void setInsertId(long insertId);

	/**
	 * Returns the update ID of this class note.
	 *
	 * @return the update ID of this class note
	 */
	public long getUpdateId();

	/**
	 * Sets the update ID of this class note.
	 *
	 * @param updateId the update ID of this class note
	 */
	public void setUpdateId(long updateId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public String[] getAvailableLanguageIds();

	public String getDefaultLanguageId();

	public void prepareLocalizedFieldsForImport() throws LocaleException;

	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.kisti.edison.virtuallaboratory.model.ClassNote classNote);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.kisti.edison.virtuallaboratory.model.ClassNote> toCacheModel();

	@Override
	public org.kisti.edison.virtuallaboratory.model.ClassNote toEscapedModel();

	@Override
	public org.kisti.edison.virtuallaboratory.model.ClassNote toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}