/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.kisti.edison.virtuallaboratory.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the VirtualLabScienceAppLink service. Represents a row in the &quot;EDVIR_VirtualLabScienceAppLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.kisti.edison.virtuallaboratory.model.impl.VirtualLabScienceAppLinkModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.kisti.edison.virtuallaboratory.model.impl.VirtualLabScienceAppLinkImpl}.
 * </p>
 *
 * @author EDISON
 * @see VirtualLabScienceAppLink
 * @see org.kisti.edison.virtuallaboratory.model.impl.VirtualLabScienceAppLinkImpl
 * @see org.kisti.edison.virtuallaboratory.model.impl.VirtualLabScienceAppLinkModelImpl
 * @generated
 */
public interface VirtualLabScienceAppLinkModel extends BaseModel<VirtualLabScienceAppLink> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a virtual lab science app link model instance should use the {@link VirtualLabScienceAppLink} interface instead.
	 */

	/**
	 * Returns the primary key of this virtual lab science app link.
	 *
	 * @return the primary key of this virtual lab science app link
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this virtual lab science app link.
	 *
	 * @param primaryKey the primary key of this virtual lab science app link
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the science app seq no of this virtual lab science app link.
	 *
	 * @return the science app seq no of this virtual lab science app link
	 */
	public long getScienceAppSeqNo();

	/**
	 * Sets the science app seq no of this virtual lab science app link.
	 *
	 * @param scienceAppSeqNo the science app seq no of this virtual lab science app link
	 */
	public void setScienceAppSeqNo(long scienceAppSeqNo);

	/**
	 * Returns the science app ID of this virtual lab science app link.
	 *
	 * @return the science app ID of this virtual lab science app link
	 */
	public long getScienceAppId();

	/**
	 * Sets the science app ID of this virtual lab science app link.
	 *
	 * @param scienceAppId the science app ID of this virtual lab science app link
	 */
	public void setScienceAppId(long scienceAppId);

	/**
	 * Returns the virtual lab ID of this virtual lab science app link.
	 *
	 * @return the virtual lab ID of this virtual lab science app link
	 */
	public long getVirtualLabId();

	/**
	 * Sets the virtual lab ID of this virtual lab science app link.
	 *
	 * @param virtualLabId the virtual lab ID of this virtual lab science app link
	 */
	public void setVirtualLabId(long virtualLabId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.kisti.edison.virtuallaboratory.model.VirtualLabScienceAppLink virtualLabScienceAppLink);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.kisti.edison.virtuallaboratory.model.VirtualLabScienceAppLink> toCacheModel();

	@Override
	public org.kisti.edison.virtuallaboratory.model.VirtualLabScienceAppLink toEscapedModel();

	@Override
	public org.kisti.edison.virtuallaboratory.model.VirtualLabScienceAppLink toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}