/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.kisti.edison.virtuallaboratory.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the VirtualLabScienceAppLinkClass service. Represents a row in the &quot;EDVIR_VirtualLabScienceAppLinkClass&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.kisti.edison.virtuallaboratory.model.impl.VirtualLabScienceAppLinkClassModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.kisti.edison.virtuallaboratory.model.impl.VirtualLabScienceAppLinkClassImpl}.
 * </p>
 *
 * @author EDISON
 * @see VirtualLabScienceAppLinkClass
 * @see org.kisti.edison.virtuallaboratory.model.impl.VirtualLabScienceAppLinkClassImpl
 * @see org.kisti.edison.virtuallaboratory.model.impl.VirtualLabScienceAppLinkClassModelImpl
 * @generated
 */
public interface VirtualLabScienceAppLinkClassModel extends BaseModel<VirtualLabScienceAppLinkClass> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a virtual lab science app link class model instance should use the {@link VirtualLabScienceAppLinkClass} interface instead.
	 */

	/**
	 * Returns the primary key of this virtual lab science app link class.
	 *
	 * @return the primary key of this virtual lab science app link class
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this virtual lab science app link class.
	 *
	 * @param primaryKey the primary key of this virtual lab science app link class
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the science app class seq no of this virtual lab science app link class.
	 *
	 * @return the science app class seq no of this virtual lab science app link class
	 */
	public long getScienceAppClassSeqNo();

	/**
	 * Sets the science app class seq no of this virtual lab science app link class.
	 *
	 * @param scienceAppClassSeqNo the science app class seq no of this virtual lab science app link class
	 */
	public void setScienceAppClassSeqNo(long scienceAppClassSeqNo);

	/**
	 * Returns the class ID of this virtual lab science app link class.
	 *
	 * @return the class ID of this virtual lab science app link class
	 */
	public long getClassId();

	/**
	 * Sets the class ID of this virtual lab science app link class.
	 *
	 * @param classId the class ID of this virtual lab science app link class
	 */
	public void setClassId(long classId);

	/**
	 * Returns the science app seq no of this virtual lab science app link class.
	 *
	 * @return the science app seq no of this virtual lab science app link class
	 */
	public long getScienceAppSeqNo();

	/**
	 * Sets the science app seq no of this virtual lab science app link class.
	 *
	 * @param scienceAppSeqNo the science app seq no of this virtual lab science app link class
	 */
	public void setScienceAppSeqNo(long scienceAppSeqNo);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.kisti.edison.virtuallaboratory.model.VirtualLabScienceAppLinkClass virtualLabScienceAppLinkClass);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.kisti.edison.virtuallaboratory.model.VirtualLabScienceAppLinkClass> toCacheModel();

	@Override
	public org.kisti.edison.virtuallaboratory.model.VirtualLabScienceAppLinkClass toEscapedModel();

	@Override
	public org.kisti.edison.virtuallaboratory.model.VirtualLabScienceAppLinkClass toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}