/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.kisti.edison.search.service.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Search service. Represents a row in the &quot;EDSEARCH_Search&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.kisti.edison.search.service.model.impl.SearchModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.kisti.edison.search.service.model.impl.SearchImpl}.
 * </p>
 *
 * @author yjpark
 * @see Search
 * @see org.kisti.edison.search.service.model.impl.SearchImpl
 * @see org.kisti.edison.search.service.model.impl.SearchModelImpl
 * @generated
 */
public interface SearchModel extends BaseModel<Search> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a search model instance should use the {@link Search} interface instead.
	 */

	/**
	 * Returns the primary key of this search.
	 *
	 * @return the primary key of this search
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this search.
	 *
	 * @param primaryKey the primary key of this search
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this search.
	 *
	 * @return the ID of this search
	 */
	public long getId();

	/**
	 * Sets the ID of this search.
	 *
	 * @param id the ID of this search
	 */
	public void setId(long id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.kisti.edison.search.service.model.Search search);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.kisti.edison.search.service.model.Search> toCacheModel();

	@Override
	public org.kisti.edison.search.service.model.Search toEscapedModel();

	@Override
	public org.kisti.edison.search.service.model.Search toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}