/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package kisti.edison.challenge.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.model.WorkflowedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ChallengeEvaluationScore service. Represents a row in the &quot;challenge_ChallengeEvaluationScore&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link kisti.edison.challenge.model.impl.ChallengeEvaluationScoreModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link kisti.edison.challenge.model.impl.ChallengeEvaluationScoreImpl}.
 * </p>
 *
 * @author KYJ
 * @see ChallengeEvaluationScore
 * @see kisti.edison.challenge.model.impl.ChallengeEvaluationScoreImpl
 * @see kisti.edison.challenge.model.impl.ChallengeEvaluationScoreModelImpl
 * @generated
 */
public interface ChallengeEvaluationScoreModel extends BaseModel<ChallengeEvaluationScore>,
	StagedGroupedModel, WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a challenge evaluation score model instance should use the {@link ChallengeEvaluationScore} interface instead.
	 */

	/**
	 * Returns the primary key of this challenge evaluation score.
	 *
	 * @return the primary key of this challenge evaluation score
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this challenge evaluation score.
	 *
	 * @param primaryKey the primary key of this challenge evaluation score
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this challenge evaluation score.
	 *
	 * @return the uuid of this challenge evaluation score
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this challenge evaluation score.
	 *
	 * @param uuid the uuid of this challenge evaluation score
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the challenge evaluation score ID of this challenge evaluation score.
	 *
	 * @return the challenge evaluation score ID of this challenge evaluation score
	 */
	public long getChallengeEvaluationScoreId();

	/**
	 * Sets the challenge evaluation score ID of this challenge evaluation score.
	 *
	 * @param challengeEvaluationScoreId the challenge evaluation score ID of this challenge evaluation score
	 */
	public void setChallengeEvaluationScoreId(long challengeEvaluationScoreId);

	/**
	 * Returns the group ID of this challenge evaluation score.
	 *
	 * @return the group ID of this challenge evaluation score
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this challenge evaluation score.
	 *
	 * @param groupId the group ID of this challenge evaluation score
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this challenge evaluation score.
	 *
	 * @return the company ID of this challenge evaluation score
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this challenge evaluation score.
	 *
	 * @param companyId the company ID of this challenge evaluation score
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this challenge evaluation score.
	 *
	 * @return the user ID of this challenge evaluation score
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this challenge evaluation score.
	 *
	 * @param userId the user ID of this challenge evaluation score
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this challenge evaluation score.
	 *
	 * @return the user uuid of this challenge evaluation score
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this challenge evaluation score.
	 *
	 * @param userUuid the user uuid of this challenge evaluation score
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this challenge evaluation score.
	 *
	 * @return the user name of this challenge evaluation score
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this challenge evaluation score.
	 *
	 * @param userName the user name of this challenge evaluation score
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this challenge evaluation score.
	 *
	 * @return the create date of this challenge evaluation score
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this challenge evaluation score.
	 *
	 * @param createDate the create date of this challenge evaluation score
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this challenge evaluation score.
	 *
	 * @return the modified date of this challenge evaluation score
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this challenge evaluation score.
	 *
	 * @param modifiedDate the modified date of this challenge evaluation score
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this challenge evaluation score.
	 *
	 * @return the status of this challenge evaluation score
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this challenge evaluation score.
	 *
	 * @param status the status of this challenge evaluation score
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this challenge evaluation score.
	 *
	 * @return the status by user ID of this challenge evaluation score
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this challenge evaluation score.
	 *
	 * @param statusByUserId the status by user ID of this challenge evaluation score
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this challenge evaluation score.
	 *
	 * @return the status by user uuid of this challenge evaluation score
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getStatusByUserUuid() throws SystemException;

	/**
	 * Sets the status by user uuid of this challenge evaluation score.
	 *
	 * @param statusByUserUuid the status by user uuid of this challenge evaluation score
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this challenge evaluation score.
	 *
	 * @return the status by user name of this challenge evaluation score
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this challenge evaluation score.
	 *
	 * @param statusByUserName the status by user name of this challenge evaluation score
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this challenge evaluation score.
	 *
	 * @return the status date of this challenge evaluation score
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this challenge evaluation score.
	 *
	 * @param statusDate the status date of this challenge evaluation score
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the score of this challenge evaluation score.
	 *
	 * @return the score of this challenge evaluation score
	 */
	public double getScore();

	/**
	 * Sets the score of this challenge evaluation score.
	 *
	 * @param score the score of this challenge evaluation score
	 */
	public void setScore(double score);

	/**
	 * Returns the challenge team ID of this challenge evaluation score.
	 *
	 * @return the challenge team ID of this challenge evaluation score
	 */
	public long getChallengeTeamId();

	/**
	 * Sets the challenge team ID of this challenge evaluation score.
	 *
	 * @param challengeTeamId the challenge team ID of this challenge evaluation score
	 */
	public void setChallengeTeamId(long challengeTeamId);

	/**
	 * Returns the challenge evaluation management ID of this challenge evaluation score.
	 *
	 * @return the challenge evaluation management ID of this challenge evaluation score
	 */
	public long getChallengeEvaluationManagementId();

	/**
	 * Sets the challenge evaluation management ID of this challenge evaluation score.
	 *
	 * @param challengeEvaluationManagementId the challenge evaluation management ID of this challenge evaluation score
	 */
	public void setChallengeEvaluationManagementId(
		long challengeEvaluationManagementId);

	/**
	 * @deprecated As of 6.1.0, replaced by {@link #isApproved()}
	 */
	@Override
	public boolean getApproved();

	/**
	 * Returns <code>true</code> if this challenge evaluation score is approved.
	 *
	 * @return <code>true</code> if this challenge evaluation score is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this challenge evaluation score is denied.
	 *
	 * @return <code>true</code> if this challenge evaluation score is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this challenge evaluation score is a draft.
	 *
	 * @return <code>true</code> if this challenge evaluation score is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this challenge evaluation score is expired.
	 *
	 * @return <code>true</code> if this challenge evaluation score is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this challenge evaluation score is inactive.
	 *
	 * @return <code>true</code> if this challenge evaluation score is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this challenge evaluation score is incomplete.
	 *
	 * @return <code>true</code> if this challenge evaluation score is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this challenge evaluation score is pending.
	 *
	 * @return <code>true</code> if this challenge evaluation score is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this challenge evaluation score is scheduled.
	 *
	 * @return <code>true</code> if this challenge evaluation score is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		kisti.edison.challenge.model.ChallengeEvaluationScore challengeEvaluationScore);

	@Override
	public int hashCode();

	@Override
	public CacheModel<kisti.edison.challenge.model.ChallengeEvaluationScore> toCacheModel();

	@Override
	public kisti.edison.challenge.model.ChallengeEvaluationScore toEscapedModel();

	@Override
	public kisti.edison.challenge.model.ChallengeEvaluationScore toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}