/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package kisti.edison.challenge.model;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.model.WorkflowedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the Challenge service. Represents a row in the &quot;challenge_Challenge&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link kisti.edison.challenge.model.impl.ChallengeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link kisti.edison.challenge.model.impl.ChallengeImpl}.
 * </p>
 *
 * @author KYJ
 * @see Challenge
 * @see kisti.edison.challenge.model.impl.ChallengeImpl
 * @see kisti.edison.challenge.model.impl.ChallengeModelImpl
 * @generated
 */
public interface ChallengeModel extends BaseModel<Challenge>, StagedGroupedModel,
	WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a challenge model instance should use the {@link Challenge} interface instead.
	 */

	/**
	 * Returns the primary key of this challenge.
	 *
	 * @return the primary key of this challenge
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this challenge.
	 *
	 * @param primaryKey the primary key of this challenge
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this challenge.
	 *
	 * @return the uuid of this challenge
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this challenge.
	 *
	 * @param uuid the uuid of this challenge
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the challenge ID of this challenge.
	 *
	 * @return the challenge ID of this challenge
	 */
	public long getChallengeId();

	/**
	 * Sets the challenge ID of this challenge.
	 *
	 * @param challengeId the challenge ID of this challenge
	 */
	public void setChallengeId(long challengeId);

	/**
	 * Returns the group ID of this challenge.
	 *
	 * @return the group ID of this challenge
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this challenge.
	 *
	 * @param groupId the group ID of this challenge
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this challenge.
	 *
	 * @return the company ID of this challenge
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this challenge.
	 *
	 * @param companyId the company ID of this challenge
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this challenge.
	 *
	 * @return the user ID of this challenge
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this challenge.
	 *
	 * @param userId the user ID of this challenge
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this challenge.
	 *
	 * @return the user uuid of this challenge
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this challenge.
	 *
	 * @param userUuid the user uuid of this challenge
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this challenge.
	 *
	 * @return the user name of this challenge
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this challenge.
	 *
	 * @param userName the user name of this challenge
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this challenge.
	 *
	 * @return the create date of this challenge
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this challenge.
	 *
	 * @param createDate the create date of this challenge
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this challenge.
	 *
	 * @return the modified date of this challenge
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this challenge.
	 *
	 * @param modifiedDate the modified date of this challenge
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this challenge.
	 *
	 * @return the status of this challenge
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this challenge.
	 *
	 * @param status the status of this challenge
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this challenge.
	 *
	 * @return the status by user ID of this challenge
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this challenge.
	 *
	 * @param statusByUserId the status by user ID of this challenge
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this challenge.
	 *
	 * @return the status by user uuid of this challenge
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getStatusByUserUuid() throws SystemException;

	/**
	 * Sets the status by user uuid of this challenge.
	 *
	 * @param statusByUserUuid the status by user uuid of this challenge
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this challenge.
	 *
	 * @return the status by user name of this challenge
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this challenge.
	 *
	 * @param statusByUserName the status by user name of this challenge
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this challenge.
	 *
	 * @return the status date of this challenge
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this challenge.
	 *
	 * @param statusDate the status date of this challenge
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the name of this challenge.
	 *
	 * @return the name of this challenge
	 */
	public String getName();

	/**
	 * Returns the localized name of this challenge in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized name of this challenge
	 */
	@AutoEscape
	public String getName(Locale locale);

	/**
	 * Returns the localized name of this challenge in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized name of this challenge. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getName(Locale locale, boolean useDefault);

	/**
	 * Returns the localized name of this challenge in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized name of this challenge
	 */
	@AutoEscape
	public String getName(String languageId);

	/**
	 * Returns the localized name of this challenge in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized name of this challenge
	 */
	@AutoEscape
	public String getName(String languageId, boolean useDefault);

	@AutoEscape
	public String getNameCurrentLanguageId();

	@AutoEscape
	public String getNameCurrentValue();

	/**
	 * Returns a map of the locales and localized names of this challenge.
	 *
	 * @return the locales and localized names of this challenge
	 */
	public Map<Locale, String> getNameMap();

	/**
	 * Sets the name of this challenge.
	 *
	 * @param name the name of this challenge
	 */
	public void setName(String name);

	/**
	 * Sets the localized name of this challenge in the language.
	 *
	 * @param name the localized name of this challenge
	 * @param locale the locale of the language
	 */
	public void setName(String name, Locale locale);

	/**
	 * Sets the localized name of this challenge in the language, and sets the default locale.
	 *
	 * @param name the localized name of this challenge
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setName(String name, Locale locale, Locale defaultLocale);

	public void setNameCurrentLanguageId(String languageId);

	/**
	 * Sets the localized names of this challenge from the map of locales and localized names.
	 *
	 * @param nameMap the locales and localized names of this challenge
	 */
	public void setNameMap(Map<Locale, String> nameMap);

	/**
	 * Sets the localized names of this challenge from the map of locales and localized names, and sets the default locale.
	 *
	 * @param nameMap the locales and localized names of this challenge
	 * @param defaultLocale the default locale
	 */
	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale);

	/**
	 * Returns the field of this challenge.
	 *
	 * @return the field of this challenge
	 */
	public String getField();

	/**
	 * Returns the localized field of this challenge in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized field of this challenge
	 */
	@AutoEscape
	public String getField(Locale locale);

	/**
	 * Returns the localized field of this challenge in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized field of this challenge. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getField(Locale locale, boolean useDefault);

	/**
	 * Returns the localized field of this challenge in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized field of this challenge
	 */
	@AutoEscape
	public String getField(String languageId);

	/**
	 * Returns the localized field of this challenge in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized field of this challenge
	 */
	@AutoEscape
	public String getField(String languageId, boolean useDefault);

	@AutoEscape
	public String getFieldCurrentLanguageId();

	@AutoEscape
	public String getFieldCurrentValue();

	/**
	 * Returns a map of the locales and localized fields of this challenge.
	 *
	 * @return the locales and localized fields of this challenge
	 */
	public Map<Locale, String> getFieldMap();

	/**
	 * Sets the field of this challenge.
	 *
	 * @param field the field of this challenge
	 */
	public void setField(String field);

	/**
	 * Sets the localized field of this challenge in the language.
	 *
	 * @param field the localized field of this challenge
	 * @param locale the locale of the language
	 */
	public void setField(String field, Locale locale);

	/**
	 * Sets the localized field of this challenge in the language, and sets the default locale.
	 *
	 * @param field the localized field of this challenge
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setField(String field, Locale locale, Locale defaultLocale);

	public void setFieldCurrentLanguageId(String languageId);

	/**
	 * Sets the localized fields of this challenge from the map of locales and localized fields.
	 *
	 * @param fieldMap the locales and localized fields of this challenge
	 */
	public void setFieldMap(Map<Locale, String> fieldMap);

	/**
	 * Sets the localized fields of this challenge from the map of locales and localized fields, and sets the default locale.
	 *
	 * @param fieldMap the locales and localized fields of this challenge
	 * @param defaultLocale the default locale
	 */
	public void setFieldMap(Map<Locale, String> fieldMap, Locale defaultLocale);

	/**
	 * Returns the description of this challenge.
	 *
	 * @return the description of this challenge
	 */
	public String getDescription();

	/**
	 * Returns the localized description of this challenge in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized description of this challenge
	 */
	@AutoEscape
	public String getDescription(Locale locale);

	/**
	 * Returns the localized description of this challenge in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this challenge. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDescription(Locale locale, boolean useDefault);

	/**
	 * Returns the localized description of this challenge in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized description of this challenge
	 */
	@AutoEscape
	public String getDescription(String languageId);

	/**
	 * Returns the localized description of this challenge in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this challenge
	 */
	@AutoEscape
	public String getDescription(String languageId, boolean useDefault);

	@AutoEscape
	public String getDescriptionCurrentLanguageId();

	@AutoEscape
	public String getDescriptionCurrentValue();

	/**
	 * Returns a map of the locales and localized descriptions of this challenge.
	 *
	 * @return the locales and localized descriptions of this challenge
	 */
	public Map<Locale, String> getDescriptionMap();

	/**
	 * Sets the description of this challenge.
	 *
	 * @param description the description of this challenge
	 */
	public void setDescription(String description);

	/**
	 * Sets the localized description of this challenge in the language.
	 *
	 * @param description the localized description of this challenge
	 * @param locale the locale of the language
	 */
	public void setDescription(String description, Locale locale);

	/**
	 * Sets the localized description of this challenge in the language, and sets the default locale.
	 *
	 * @param description the localized description of this challenge
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDescription(String description, Locale locale,
		Locale defaultLocale);

	public void setDescriptionCurrentLanguageId(String languageId);

	/**
	 * Sets the localized descriptions of this challenge from the map of locales and localized descriptions.
	 *
	 * @param descriptionMap the locales and localized descriptions of this challenge
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap);

	/**
	 * Sets the localized descriptions of this challenge from the map of locales and localized descriptions, and sets the default locale.
	 *
	 * @param descriptionMap the locales and localized descriptions of this challenge
	 * @param defaultLocale the default locale
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap,
		Locale defaultLocale);

	/**
	 * @deprecated As of 6.1.0, replaced by {@link #isApproved()}
	 */
	@Override
	public boolean getApproved();

	/**
	 * Returns <code>true</code> if this challenge is approved.
	 *
	 * @return <code>true</code> if this challenge is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this challenge is denied.
	 *
	 * @return <code>true</code> if this challenge is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this challenge is a draft.
	 *
	 * @return <code>true</code> if this challenge is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this challenge is expired.
	 *
	 * @return <code>true</code> if this challenge is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this challenge is inactive.
	 *
	 * @return <code>true</code> if this challenge is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this challenge is incomplete.
	 *
	 * @return <code>true</code> if this challenge is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this challenge is pending.
	 *
	 * @return <code>true</code> if this challenge is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this challenge is scheduled.
	 *
	 * @return <code>true</code> if this challenge is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public String[] getAvailableLanguageIds();

	public String getDefaultLanguageId();

	public void prepareLocalizedFieldsForImport() throws LocaleException;

	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(kisti.edison.challenge.model.Challenge challenge);

	@Override
	public int hashCode();

	@Override
	public CacheModel<kisti.edison.challenge.model.Challenge> toCacheModel();

	@Override
	public kisti.edison.challenge.model.Challenge toEscapedModel();

	@Override
	public kisti.edison.challenge.model.Challenge toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}