/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.kisti.edison.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import org.kisti.edison.service.persistence.SimulationJobPK;

import java.io.Serializable;

/**
 * The base model interface for the SimulationJob service. Represents a row in the &quot;EDOV_SimulationJob&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.kisti.edison.model.impl.SimulationJobModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.kisti.edison.model.impl.SimulationJobImpl}.
 * </p>
 *
 * @author edison
 * @see SimulationJob
 * @see org.kisti.edison.model.impl.SimulationJobImpl
 * @see org.kisti.edison.model.impl.SimulationJobModelImpl
 * @generated
 */
public interface SimulationJobModel extends BaseModel<SimulationJob> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a simulation job model instance should use the {@link SimulationJob} interface instead.
	 */

	/**
	 * Returns the primary key of this simulation job.
	 *
	 * @return the primary key of this simulation job
	 */
	public SimulationJobPK getPrimaryKey();

	/**
	 * Sets the primary key of this simulation job.
	 *
	 * @param primaryKey the primary key of this simulation job
	 */
	public void setPrimaryKey(SimulationJobPK primaryKey);

	/**
	 * Returns the create date of this simulation job.
	 *
	 * @return the create date of this simulation job
	 */
	@AutoEscape
	public String getCreateDate();

	/**
	 * Sets the create date of this simulation job.
	 *
	 * @param createDate the create date of this simulation job
	 */
	public void setCreateDate(String createDate);

	/**
	 * Returns the group ID of this simulation job.
	 *
	 * @return the group ID of this simulation job
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this simulation job.
	 *
	 * @param groupId the group ID of this simulation job
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the cnt of this simulation job.
	 *
	 * @return the cnt of this simulation job
	 */
	public Long getCnt();

	/**
	 * Sets the cnt of this simulation job.
	 *
	 * @param cnt the cnt of this simulation job
	 */
	public void setCnt(Long cnt);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.kisti.edison.model.SimulationJob simulationJob);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.kisti.edison.model.SimulationJob> toCacheModel();

	@Override
	public org.kisti.edison.model.SimulationJob toEscapedModel();

	@Override
	public org.kisti.edison.model.SimulationJob toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}