/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.kisti.edison.science.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.TypedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import org.kisti.edison.science.service.persistence.ScienceAppRatingsEntryPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ScienceAppRatingsEntry service. Represents a row in the &quot;EDAPP_ScienceAppRatingsEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.kisti.edison.science.model.impl.ScienceAppRatingsEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.kisti.edison.science.model.impl.ScienceAppRatingsEntryImpl}.
 * </p>
 *
 * @author EDISON
 * @see ScienceAppRatingsEntry
 * @see org.kisti.edison.science.model.impl.ScienceAppRatingsEntryImpl
 * @see org.kisti.edison.science.model.impl.ScienceAppRatingsEntryModelImpl
 * @generated
 */
public interface ScienceAppRatingsEntryModel extends AuditedModel,
	BaseModel<ScienceAppRatingsEntry>, TypedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a science app ratings entry model instance should use the {@link ScienceAppRatingsEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this science app ratings entry.
	 *
	 * @return the primary key of this science app ratings entry
	 */
	public ScienceAppRatingsEntryPK getPrimaryKey();

	/**
	 * Sets the primary key of this science app ratings entry.
	 *
	 * @param primaryKey the primary key of this science app ratings entry
	 */
	public void setPrimaryKey(ScienceAppRatingsEntryPK primaryKey);

	/**
	 * Returns the user ID of this science app ratings entry.
	 *
	 * @return the user ID of this science app ratings entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this science app ratings entry.
	 *
	 * @param userId the user ID of this science app ratings entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this science app ratings entry.
	 *
	 * @return the user uuid of this science app ratings entry
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this science app ratings entry.
	 *
	 * @param userUuid the user uuid of this science app ratings entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the science app ID of this science app ratings entry.
	 *
	 * @return the science app ID of this science app ratings entry
	 */
	public long getScienceAppId();

	/**
	 * Sets the science app ID of this science app ratings entry.
	 *
	 * @param scienceAppId the science app ID of this science app ratings entry
	 */
	public void setScienceAppId(long scienceAppId);

	/**
	 * Returns the company ID of this science app ratings entry.
	 *
	 * @return the company ID of this science app ratings entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this science app ratings entry.
	 *
	 * @param companyId the company ID of this science app ratings entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user name of this science app ratings entry.
	 *
	 * @return the user name of this science app ratings entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this science app ratings entry.
	 *
	 * @param userName the user name of this science app ratings entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this science app ratings entry.
	 *
	 * @return the create date of this science app ratings entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this science app ratings entry.
	 *
	 * @param createDate the create date of this science app ratings entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this science app ratings entry.
	 *
	 * @return the modified date of this science app ratings entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this science app ratings entry.
	 *
	 * @param modifiedDate the modified date of this science app ratings entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the fully qualified class name of this science app ratings entry.
	 *
	 * @return the fully qualified class name of this science app ratings entry
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this science app ratings entry.
	 *
	 * @return the class name ID of this science app ratings entry
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this science app ratings entry.
	 *
	 * @param classNameId the class name ID of this science app ratings entry
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the score of this science app ratings entry.
	 *
	 * @return the score of this science app ratings entry
	 */
	public long getScore();

	/**
	 * Sets the score of this science app ratings entry.
	 *
	 * @param score the score of this science app ratings entry
	 */
	public void setScore(long score);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.kisti.edison.science.model.ScienceAppRatingsEntry scienceAppRatingsEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.kisti.edison.science.model.ScienceAppRatingsEntry> toCacheModel();

	@Override
	public org.kisti.edison.science.model.ScienceAppRatingsEntry toEscapedModel();

	@Override
	public org.kisti.edison.science.model.ScienceAppRatingsEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}