/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.kisti.edison.science.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import org.kisti.edison.science.service.persistence.ScienceAppPaperPK;

import java.io.Serializable;

/**
 * The base model interface for the ScienceAppPaper service. Represents a row in the &quot;EDAPP_ScienceAppPaper&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.kisti.edison.science.model.impl.ScienceAppPaperModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.kisti.edison.science.model.impl.ScienceAppPaperImpl}.
 * </p>
 *
 * @author EDISON
 * @see ScienceAppPaper
 * @see org.kisti.edison.science.model.impl.ScienceAppPaperImpl
 * @see org.kisti.edison.science.model.impl.ScienceAppPaperModelImpl
 * @generated
 */
public interface ScienceAppPaperModel extends BaseModel<ScienceAppPaper> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a science app paper model instance should use the {@link ScienceAppPaper} interface instead.
	 */

	/**
	 * Returns the primary key of this science app paper.
	 *
	 * @return the primary key of this science app paper
	 */
	public ScienceAppPaperPK getPrimaryKey();

	/**
	 * Sets the primary key of this science app paper.
	 *
	 * @param primaryKey the primary key of this science app paper
	 */
	public void setPrimaryKey(ScienceAppPaperPK primaryKey);

	/**
	 * Returns the science app ID of this science app paper.
	 *
	 * @return the science app ID of this science app paper
	 */
	public long getScienceAppId();

	/**
	 * Sets the science app ID of this science app paper.
	 *
	 * @param scienceAppId the science app ID of this science app paper
	 */
	public void setScienceAppId(long scienceAppId);

	/**
	 * Returns the paper seq of this science app paper.
	 *
	 * @return the paper seq of this science app paper
	 */
	public long getPaperSeq();

	/**
	 * Sets the paper seq of this science app paper.
	 *
	 * @param paperSeq the paper seq of this science app paper
	 */
	public void setPaperSeq(long paperSeq);

	/**
	 * Returns the paper type of this science app paper.
	 *
	 * @return the paper type of this science app paper
	 */
	@AutoEscape
	public String getPaperType();

	/**
	 * Sets the paper type of this science app paper.
	 *
	 * @param paperType the paper type of this science app paper
	 */
	public void setPaperType(String paperType);

	/**
	 * Returns the paper value of this science app paper.
	 *
	 * @return the paper value of this science app paper
	 */
	@AutoEscape
	public String getPaperValue();

	/**
	 * Sets the paper value of this science app paper.
	 *
	 * @param paperValue the paper value of this science app paper
	 */
	public void setPaperValue(String paperValue);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.kisti.edison.science.model.ScienceAppPaper scienceAppPaper);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.kisti.edison.science.model.ScienceAppPaper> toCacheModel();

	@Override
	public org.kisti.edison.science.model.ScienceAppPaper toEscapedModel();

	@Override
	public org.kisti.edison.science.model.ScienceAppPaper toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}