/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package edison.challenge.service.builder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Awardhistory service. Represents a row in the &quot;edison_Awardhistory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link edison.challenge.service.builder.model.impl.AwardhistoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link edison.challenge.service.builder.model.impl.AwardhistoryImpl}.
 * </p>
 *
 * @author kyj
 * @see Awardhistory
 * @see edison.challenge.service.builder.model.impl.AwardhistoryImpl
 * @see edison.challenge.service.builder.model.impl.AwardhistoryModelImpl
 * @generated
 */
public interface AwardhistoryModel extends BaseModel<Awardhistory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a awardhistory model instance should use the {@link Awardhistory} interface instead.
	 */

	/**
	 * Returns the primary key of this awardhistory.
	 *
	 * @return the primary key of this awardhistory
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this awardhistory.
	 *
	 * @param primaryKey the primary key of this awardhistory
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the awardhistoryid of this awardhistory.
	 *
	 * @return the awardhistoryid of this awardhistory
	 */
	public long getAwardhistoryid();

	/**
	 * Sets the awardhistoryid of this awardhistory.
	 *
	 * @param awardhistoryid the awardhistoryid of this awardhistory
	 */
	public void setAwardhistoryid(long awardhistoryid);

	/**
	 * Returns the name of this awardhistory.
	 *
	 * @return the name of this awardhistory
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this awardhistory.
	 *
	 * @param name the name of this awardhistory
	 */
	public void setName(String name);

	/**
	 * Returns the prize of this awardhistory.
	 *
	 * @return the prize of this awardhistory
	 */
	@AutoEscape
	public String getPrize();

	/**
	 * Sets the prize of this awardhistory.
	 *
	 * @param prize the prize of this awardhistory
	 */
	public void setPrize(String prize);

	/**
	 * Returns the ch teamid of this awardhistory.
	 *
	 * @return the ch teamid of this awardhistory
	 */
	public long getChTeamid();

	/**
	 * Sets the ch teamid of this awardhistory.
	 *
	 * @param chTeamid the ch teamid of this awardhistory
	 */
	public void setChTeamid(long chTeamid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		edison.challenge.service.builder.model.Awardhistory awardhistory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<edison.challenge.service.builder.model.Awardhistory> toCacheModel();

	@Override
	public edison.challenge.service.builder.model.Awardhistory toEscapedModel();

	@Override
	public edison.challenge.service.builder.model.Awardhistory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}