/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package edison.challenge.service.builder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Member service. Represents a row in the &quot;edison_Member&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link edison.challenge.service.builder.model.impl.MemberModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link edison.challenge.service.builder.model.impl.MemberImpl}.
 * </p>
 *
 * @author kyj
 * @see Member
 * @see edison.challenge.service.builder.model.impl.MemberImpl
 * @see edison.challenge.service.builder.model.impl.MemberModelImpl
 * @generated
 */
public interface MemberModel extends BaseModel<Member> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a member model instance should use the {@link Member} interface instead.
	 */

	/**
	 * Returns the primary key of this member.
	 *
	 * @return the primary key of this member
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this member.
	 *
	 * @param primaryKey the primary key of this member
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the memberid of this member.
	 *
	 * @return the memberid of this member
	 */
	@AutoEscape
	public String getMemberid();

	/**
	 * Sets the memberid of this member.
	 *
	 * @param memberid the memberid of this member
	 */
	public void setMemberid(String memberid);

	/**
	 * Returns the name of this member.
	 *
	 * @return the name of this member
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this member.
	 *
	 * @param name the name of this member
	 */
	public void setName(String name);

	/**
	 * Returns the leader of this member.
	 *
	 * @return the leader of this member
	 */
	public boolean getLeader();

	/**
	 * Returns <code>true</code> if this member is leader.
	 *
	 * @return <code>true</code> if this member is leader; <code>false</code> otherwise
	 */
	public boolean isLeader();

	/**
	 * Sets whether this member is leader.
	 *
	 * @param leader the leader of this member
	 */
	public void setLeader(boolean leader);

	/**
	 * Returns the falculty of this member.
	 *
	 * @return the falculty of this member
	 */
	@AutoEscape
	public String getFalculty();

	/**
	 * Sets the falculty of this member.
	 *
	 * @param falculty the falculty of this member
	 */
	public void setFalculty(String falculty);

	/**
	 * Returns the major of this member.
	 *
	 * @return the major of this member
	 */
	@AutoEscape
	public String getMajor();

	/**
	 * Sets the major of this member.
	 *
	 * @param major the major of this member
	 */
	public void setMajor(String major);

	/**
	 * Returns the grade of this member.
	 *
	 * @return the grade of this member
	 */
	@AutoEscape
	public String getGrade();

	/**
	 * Sets the grade of this member.
	 *
	 * @param grade the grade of this member
	 */
	public void setGrade(String grade);

	/**
	 * Returns the teamid of this member.
	 *
	 * @return the teamid of this member
	 */
	public long getTeamid();

	/**
	 * Sets the teamid of this member.
	 *
	 * @param teamid the teamid of this member
	 */
	public void setTeamid(long teamid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(edison.challenge.service.builder.model.Member member);

	@Override
	public int hashCode();

	@Override
	public CacheModel<edison.challenge.service.builder.model.Member> toCacheModel();

	@Override
	public edison.challenge.service.builder.model.Member toEscapedModel();

	@Override
	public edison.challenge.service.builder.model.Member toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}