/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kisti.osp.icecap.model.impl;

import com.kisti.osp.icecap.model.DataTypeStructure;
import com.kisti.osp.icecap.model.DataTypeStructureModel;
import com.kisti.osp.icecap.model.DataTypeStructureSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the DataTypeStructure service. Represents a row in the &quot;icecap_DataTypeStructure&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.kisti.osp.icecap.model.DataTypeStructureModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DataTypeStructureImpl}.
 * </p>
 *
 * @author Young-K. Suh and Jerry H. Seo
 * @see DataTypeStructureImpl
 * @see com.kisti.osp.icecap.model.DataTypeStructure
 * @see com.kisti.osp.icecap.model.DataTypeStructureModel
 * @generated
 */
@JSON(strict = true)
public class DataTypeStructureModelImpl extends BaseModelImpl<DataTypeStructure>
	implements DataTypeStructureModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a data type structure model instance should use the {@link com.kisti.osp.icecap.model.DataTypeStructure} interface instead.
	 */
	public static final String TABLE_NAME = "icecap_DataTypeStructure";
	public static final Object[][] TABLE_COLUMNS = {
			{ "typeId", Types.BIGINT },
			{ "structure", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table icecap_DataTypeStructure (typeId LONG not null primary key,structure TEXT null)";
	public static final String TABLE_SQL_DROP = "drop table icecap_DataTypeStructure";
	public static final String ORDER_BY_JPQL = " ORDER BY dataTypeStructure.typeId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY icecap_DataTypeStructure.typeId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.kisti.osp.icecap.model.DataTypeStructure"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.kisti.osp.icecap.model.DataTypeStructure"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.kisti.osp.icecap.model.DataTypeStructure"),
			true);
	public static long STRUCTURE_COLUMN_BITMASK = 1L;
	public static long TYPEID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static DataTypeStructure toModel(DataTypeStructureSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		DataTypeStructure model = new DataTypeStructureImpl();

		model.setTypeId(soapModel.getTypeId());
		model.setStructure(soapModel.getStructure());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<DataTypeStructure> toModels(
		DataTypeStructureSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<DataTypeStructure> models = new ArrayList<DataTypeStructure>(soapModels.length);

		for (DataTypeStructureSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.kisti.osp.icecap.model.DataTypeStructure"));

	public DataTypeStructureModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _typeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTypeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _typeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DataTypeStructure.class;
	}

	@Override
	public String getModelClassName() {
		return DataTypeStructure.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("typeId", getTypeId());
		attributes.put("structure", getStructure());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long typeId = (Long)attributes.get("typeId");

		if (typeId != null) {
			setTypeId(typeId);
		}

		String structure = (String)attributes.get("structure");

		if (structure != null) {
			setStructure(structure);
		}
	}

	@JSON(include = false)
	@Override
	public long getTypeId() {
		return _typeId;
	}

	@Override
	public void setTypeId(long typeId) {
		_columnBitmask |= TYPEID_COLUMN_BITMASK;

		if (!_setOriginalTypeId) {
			_setOriginalTypeId = true;

			_originalTypeId = _typeId;
		}

		_typeId = typeId;
	}

	public long getOriginalTypeId() {
		return _originalTypeId;
	}

	@JSON
	@Override
	public String getStructure() {
		if (_structure == null) {
			return StringPool.BLANK;
		}
		else {
			return _structure;
		}
	}

	@Override
	public void setStructure(String structure) {
		_columnBitmask |= STRUCTURE_COLUMN_BITMASK;

		if (_originalStructure == null) {
			_originalStructure = _structure;
		}

		_structure = structure;
	}

	public String getOriginalStructure() {
		return GetterUtil.getString(_originalStructure);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			DataTypeStructure.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DataTypeStructure toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (DataTypeStructure)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DataTypeStructureImpl dataTypeStructureImpl = new DataTypeStructureImpl();

		dataTypeStructureImpl.setTypeId(getTypeId());
		dataTypeStructureImpl.setStructure(getStructure());

		dataTypeStructureImpl.resetOriginalValues();

		return dataTypeStructureImpl;
	}

	@Override
	public int compareTo(DataTypeStructure dataTypeStructure) {
		long primaryKey = dataTypeStructure.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DataTypeStructure)) {
			return false;
		}

		DataTypeStructure dataTypeStructure = (DataTypeStructure)obj;

		long primaryKey = dataTypeStructure.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		DataTypeStructureModelImpl dataTypeStructureModelImpl = this;

		dataTypeStructureModelImpl._originalTypeId = dataTypeStructureModelImpl._typeId;

		dataTypeStructureModelImpl._setOriginalTypeId = false;

		dataTypeStructureModelImpl._originalStructure = dataTypeStructureModelImpl._structure;

		dataTypeStructureModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<DataTypeStructure> toCacheModel() {
		DataTypeStructureCacheModel dataTypeStructureCacheModel = new DataTypeStructureCacheModel();

		dataTypeStructureCacheModel.typeId = getTypeId();

		dataTypeStructureCacheModel.structure = getStructure();

		String structure = dataTypeStructureCacheModel.structure;

		if ((structure != null) && (structure.length() == 0)) {
			dataTypeStructureCacheModel.structure = null;
		}

		return dataTypeStructureCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{typeId=");
		sb.append(getTypeId());
		sb.append(", structure=");
		sb.append(getStructure());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.kisti.osp.icecap.model.DataTypeStructure");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>typeId</column-name><column-value><![CDATA[");
		sb.append(getTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>structure</column-name><column-value><![CDATA[");
		sb.append(getStructure());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DataTypeStructure.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			DataTypeStructure.class
		};
	private long _typeId;
	private long _originalTypeId;
	private boolean _setOriginalTypeId;
	private String _structure;
	private String _originalStructure;
	private long _columnBitmask;
	private DataTypeStructure _escapedModel;
}