/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package kisti.edison.challenge.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.workflow.WorkflowConstants;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import kisti.edison.challenge.model.ChallengeEvaluationScore;
import kisti.edison.challenge.model.ChallengeEvaluationScoreModel;
import kisti.edison.challenge.model.ChallengeEvaluationScoreSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ChallengeEvaluationScore service. Represents a row in the &quot;challenge_ChallengeEvaluationScore&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link kisti.edison.challenge.model.ChallengeEvaluationScoreModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ChallengeEvaluationScoreImpl}.
 * </p>
 *
 * @author KYJ
 * @see ChallengeEvaluationScoreImpl
 * @see kisti.edison.challenge.model.ChallengeEvaluationScore
 * @see kisti.edison.challenge.model.ChallengeEvaluationScoreModel
 * @generated
 */
@JSON(strict = true)
public class ChallengeEvaluationScoreModelImpl extends BaseModelImpl<ChallengeEvaluationScore>
	implements ChallengeEvaluationScoreModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a challenge evaluation score model instance should use the {@link kisti.edison.challenge.model.ChallengeEvaluationScore} interface instead.
	 */
	public static final String TABLE_NAME = "challenge_ChallengeEvaluationScore";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "challengeEvaluationScoreId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "status", Types.INTEGER },
			{ "statusByUserId", Types.BIGINT },
			{ "statusByUserName", Types.VARCHAR },
			{ "statusDate", Types.TIMESTAMP },
			{ "score", Types.DOUBLE },
			{ "challengeTeamId", Types.BIGINT },
			{ "challengeEvaluationManagementId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table challenge_ChallengeEvaluationScore (uuid_ VARCHAR(75) null,challengeEvaluationScoreId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,score DOUBLE,challengeTeamId LONG,challengeEvaluationManagementId LONG)";
	public static final String TABLE_SQL_DROP = "drop table challenge_ChallengeEvaluationScore";
	public static final String ORDER_BY_JPQL = " ORDER BY challengeEvaluationScore.challengeEvaluationScoreId ASC, challengeEvaluationScore.createDate ASC";
	public static final String ORDER_BY_SQL = " ORDER BY challenge_ChallengeEvaluationScore.challengeEvaluationScoreId ASC, challenge_ChallengeEvaluationScore.createDate ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.kisti.edison.challenge.model.ChallengeEvaluationScore"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.kisti.edison.challenge.model.ChallengeEvaluationScore"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.kisti.edison.challenge.model.ChallengeEvaluationScore"),
			true);
	public static long CHALLENGEEVALUATIONMANAGEMENTID_COLUMN_BITMASK = 1L;
	public static long CHALLENGETEAMID_COLUMN_BITMASK = 2L;
	public static long COMPANYID_COLUMN_BITMASK = 4L;
	public static long GROUPID_COLUMN_BITMASK = 8L;
	public static long USERID_COLUMN_BITMASK = 16L;
	public static long UUID_COLUMN_BITMASK = 32L;
	public static long CHALLENGEEVALUATIONSCOREID_COLUMN_BITMASK = 64L;
	public static long CREATEDATE_COLUMN_BITMASK = 128L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ChallengeEvaluationScore toModel(
		ChallengeEvaluationScoreSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ChallengeEvaluationScore model = new ChallengeEvaluationScoreImpl();

		model.setUuid(soapModel.getUuid());
		model.setChallengeEvaluationScoreId(soapModel.getChallengeEvaluationScoreId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setScore(soapModel.getScore());
		model.setChallengeTeamId(soapModel.getChallengeTeamId());
		model.setChallengeEvaluationManagementId(soapModel.getChallengeEvaluationManagementId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ChallengeEvaluationScore> toModels(
		ChallengeEvaluationScoreSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ChallengeEvaluationScore> models = new ArrayList<ChallengeEvaluationScore>(soapModels.length);

		for (ChallengeEvaluationScoreSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.kisti.edison.challenge.model.ChallengeEvaluationScore"));

	public ChallengeEvaluationScoreModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _challengeEvaluationScoreId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setChallengeEvaluationScoreId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _challengeEvaluationScoreId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ChallengeEvaluationScore.class;
	}

	@Override
	public String getModelClassName() {
		return ChallengeEvaluationScore.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("challengeEvaluationScoreId",
			getChallengeEvaluationScoreId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("status", getStatus());
		attributes.put("statusByUserId", getStatusByUserId());
		attributes.put("statusByUserName", getStatusByUserName());
		attributes.put("statusDate", getStatusDate());
		attributes.put("score", getScore());
		attributes.put("challengeTeamId", getChallengeTeamId());
		attributes.put("challengeEvaluationManagementId",
			getChallengeEvaluationManagementId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long challengeEvaluationScoreId = (Long)attributes.get(
				"challengeEvaluationScoreId");

		if (challengeEvaluationScoreId != null) {
			setChallengeEvaluationScoreId(challengeEvaluationScoreId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Long statusByUserId = (Long)attributes.get("statusByUserId");

		if (statusByUserId != null) {
			setStatusByUserId(statusByUserId);
		}

		String statusByUserName = (String)attributes.get("statusByUserName");

		if (statusByUserName != null) {
			setStatusByUserName(statusByUserName);
		}

		Date statusDate = (Date)attributes.get("statusDate");

		if (statusDate != null) {
			setStatusDate(statusDate);
		}

		Double score = (Double)attributes.get("score");

		if (score != null) {
			setScore(score);
		}

		Long challengeTeamId = (Long)attributes.get("challengeTeamId");

		if (challengeTeamId != null) {
			setChallengeTeamId(challengeTeamId);
		}

		Long challengeEvaluationManagementId = (Long)attributes.get(
				"challengeEvaluationManagementId");

		if (challengeEvaluationManagementId != null) {
			setChallengeEvaluationManagementId(challengeEvaluationManagementId);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getChallengeEvaluationScoreId() {
		return _challengeEvaluationScoreId;
	}

	@Override
	public void setChallengeEvaluationScoreId(long challengeEvaluationScoreId) {
		_columnBitmask = -1L;

		_challengeEvaluationScoreId = challengeEvaluationScoreId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getStatusByUserId(), "uuid",
			_statusByUserUuid);
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
		_statusByUserUuid = statusByUserUuid;
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return StringPool.BLANK;
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@JSON
	@Override
	public double getScore() {
		return _score;
	}

	@Override
	public void setScore(double score) {
		_score = score;
	}

	@JSON
	@Override
	public long getChallengeTeamId() {
		return _challengeTeamId;
	}

	@Override
	public void setChallengeTeamId(long challengeTeamId) {
		_columnBitmask |= CHALLENGETEAMID_COLUMN_BITMASK;

		if (!_setOriginalChallengeTeamId) {
			_setOriginalChallengeTeamId = true;

			_originalChallengeTeamId = _challengeTeamId;
		}

		_challengeTeamId = challengeTeamId;
	}

	public long getOriginalChallengeTeamId() {
		return _originalChallengeTeamId;
	}

	@JSON
	@Override
	public long getChallengeEvaluationManagementId() {
		return _challengeEvaluationManagementId;
	}

	@Override
	public void setChallengeEvaluationManagementId(
		long challengeEvaluationManagementId) {
		_columnBitmask |= CHALLENGEEVALUATIONMANAGEMENTID_COLUMN_BITMASK;

		if (!_setOriginalChallengeEvaluationManagementId) {
			_setOriginalChallengeEvaluationManagementId = true;

			_originalChallengeEvaluationManagementId = _challengeEvaluationManagementId;
		}

		_challengeEvaluationManagementId = challengeEvaluationManagementId;
	}

	public long getOriginalChallengeEvaluationManagementId() {
		return _originalChallengeEvaluationManagementId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				ChallengeEvaluationScore.class.getName()));
	}

	/**
	 * @deprecated As of 6.1.0, replaced by {@link #isApproved}
	 */
	@Override
	public boolean getApproved() {
		return isApproved();
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ChallengeEvaluationScore.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ChallengeEvaluationScore toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ChallengeEvaluationScore)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ChallengeEvaluationScoreImpl challengeEvaluationScoreImpl = new ChallengeEvaluationScoreImpl();

		challengeEvaluationScoreImpl.setUuid(getUuid());
		challengeEvaluationScoreImpl.setChallengeEvaluationScoreId(getChallengeEvaluationScoreId());
		challengeEvaluationScoreImpl.setGroupId(getGroupId());
		challengeEvaluationScoreImpl.setCompanyId(getCompanyId());
		challengeEvaluationScoreImpl.setUserId(getUserId());
		challengeEvaluationScoreImpl.setUserName(getUserName());
		challengeEvaluationScoreImpl.setCreateDate(getCreateDate());
		challengeEvaluationScoreImpl.setModifiedDate(getModifiedDate());
		challengeEvaluationScoreImpl.setStatus(getStatus());
		challengeEvaluationScoreImpl.setStatusByUserId(getStatusByUserId());
		challengeEvaluationScoreImpl.setStatusByUserName(getStatusByUserName());
		challengeEvaluationScoreImpl.setStatusDate(getStatusDate());
		challengeEvaluationScoreImpl.setScore(getScore());
		challengeEvaluationScoreImpl.setChallengeTeamId(getChallengeTeamId());
		challengeEvaluationScoreImpl.setChallengeEvaluationManagementId(getChallengeEvaluationManagementId());

		challengeEvaluationScoreImpl.resetOriginalValues();

		return challengeEvaluationScoreImpl;
	}

	@Override
	public int compareTo(ChallengeEvaluationScore challengeEvaluationScore) {
		int value = 0;

		if (getChallengeEvaluationScoreId() < challengeEvaluationScore.getChallengeEvaluationScoreId()) {
			value = -1;
		}
		else if (getChallengeEvaluationScoreId() > challengeEvaluationScore.getChallengeEvaluationScoreId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		value = DateUtil.compareTo(getCreateDate(),
				challengeEvaluationScore.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ChallengeEvaluationScore)) {
			return false;
		}

		ChallengeEvaluationScore challengeEvaluationScore = (ChallengeEvaluationScore)obj;

		long primaryKey = challengeEvaluationScore.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ChallengeEvaluationScoreModelImpl challengeEvaluationScoreModelImpl = this;

		challengeEvaluationScoreModelImpl._originalUuid = challengeEvaluationScoreModelImpl._uuid;

		challengeEvaluationScoreModelImpl._originalGroupId = challengeEvaluationScoreModelImpl._groupId;

		challengeEvaluationScoreModelImpl._setOriginalGroupId = false;

		challengeEvaluationScoreModelImpl._originalCompanyId = challengeEvaluationScoreModelImpl._companyId;

		challengeEvaluationScoreModelImpl._setOriginalCompanyId = false;

		challengeEvaluationScoreModelImpl._originalUserId = challengeEvaluationScoreModelImpl._userId;

		challengeEvaluationScoreModelImpl._setOriginalUserId = false;

		challengeEvaluationScoreModelImpl._originalChallengeTeamId = challengeEvaluationScoreModelImpl._challengeTeamId;

		challengeEvaluationScoreModelImpl._setOriginalChallengeTeamId = false;

		challengeEvaluationScoreModelImpl._originalChallengeEvaluationManagementId = challengeEvaluationScoreModelImpl._challengeEvaluationManagementId;

		challengeEvaluationScoreModelImpl._setOriginalChallengeEvaluationManagementId = false;

		challengeEvaluationScoreModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ChallengeEvaluationScore> toCacheModel() {
		ChallengeEvaluationScoreCacheModel challengeEvaluationScoreCacheModel = new ChallengeEvaluationScoreCacheModel();

		challengeEvaluationScoreCacheModel.uuid = getUuid();

		String uuid = challengeEvaluationScoreCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			challengeEvaluationScoreCacheModel.uuid = null;
		}

		challengeEvaluationScoreCacheModel.challengeEvaluationScoreId = getChallengeEvaluationScoreId();

		challengeEvaluationScoreCacheModel.groupId = getGroupId();

		challengeEvaluationScoreCacheModel.companyId = getCompanyId();

		challengeEvaluationScoreCacheModel.userId = getUserId();

		challengeEvaluationScoreCacheModel.userName = getUserName();

		String userName = challengeEvaluationScoreCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			challengeEvaluationScoreCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			challengeEvaluationScoreCacheModel.createDate = createDate.getTime();
		}
		else {
			challengeEvaluationScoreCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			challengeEvaluationScoreCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			challengeEvaluationScoreCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		challengeEvaluationScoreCacheModel.status = getStatus();

		challengeEvaluationScoreCacheModel.statusByUserId = getStatusByUserId();

		challengeEvaluationScoreCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = challengeEvaluationScoreCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			challengeEvaluationScoreCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			challengeEvaluationScoreCacheModel.statusDate = statusDate.getTime();
		}
		else {
			challengeEvaluationScoreCacheModel.statusDate = Long.MIN_VALUE;
		}

		challengeEvaluationScoreCacheModel.score = getScore();

		challengeEvaluationScoreCacheModel.challengeTeamId = getChallengeTeamId();

		challengeEvaluationScoreCacheModel.challengeEvaluationManagementId = getChallengeEvaluationManagementId();

		return challengeEvaluationScoreCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(31);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", challengeEvaluationScoreId=");
		sb.append(getChallengeEvaluationScoreId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", statusByUserId=");
		sb.append(getStatusByUserId());
		sb.append(", statusByUserName=");
		sb.append(getStatusByUserName());
		sb.append(", statusDate=");
		sb.append(getStatusDate());
		sb.append(", score=");
		sb.append(getScore());
		sb.append(", challengeTeamId=");
		sb.append(getChallengeTeamId());
		sb.append(", challengeEvaluationManagementId=");
		sb.append(getChallengeEvaluationManagementId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(49);

		sb.append("<model><model-name>");
		sb.append("kisti.edison.challenge.model.ChallengeEvaluationScore");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>challengeEvaluationScoreId</column-name><column-value><![CDATA[");
		sb.append(getChallengeEvaluationScoreId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserId</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserName</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusDate</column-name><column-value><![CDATA[");
		sb.append(getStatusDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>score</column-name><column-value><![CDATA[");
		sb.append(getScore());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>challengeTeamId</column-name><column-value><![CDATA[");
		sb.append(getChallengeTeamId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>challengeEvaluationManagementId</column-name><column-value><![CDATA[");
		sb.append(getChallengeEvaluationManagementId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ChallengeEvaluationScore.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ChallengeEvaluationScore.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _challengeEvaluationScoreId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserUuid;
	private String _statusByUserName;
	private Date _statusDate;
	private double _score;
	private long _challengeTeamId;
	private long _originalChallengeTeamId;
	private boolean _setOriginalChallengeTeamId;
	private long _challengeEvaluationManagementId;
	private long _originalChallengeEvaluationManagementId;
	private boolean _setOriginalChallengeEvaluationManagementId;
	private long _columnBitmask;
	private ChallengeEvaluationScore _escapedModel;
}