/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package kisti.edison.challenge.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import kisti.edison.challenge.model.ChallengeEvaluationManagement;
import kisti.edison.challenge.service.ChallengeEvaluationManagementLocalServiceUtil;

/**
 * The extended model base implementation for the ChallengeEvaluationManagement service. Represents a row in the &quot;challenge_ChallengeEvaluationManagement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ChallengeEvaluationManagementImpl}.
 * </p>
 *
 * @author KYJ
 * @see ChallengeEvaluationManagementImpl
 * @see kisti.edison.challenge.model.ChallengeEvaluationManagement
 * @generated
 */
public abstract class ChallengeEvaluationManagementBaseImpl
	extends ChallengeEvaluationManagementModelImpl
	implements ChallengeEvaluationManagement {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a challenge evaluation management model instance should use the {@link ChallengeEvaluationManagement} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			ChallengeEvaluationManagementLocalServiceUtil.addChallengeEvaluationManagement(this);
		}
		else {
			ChallengeEvaluationManagementLocalServiceUtil.updateChallengeEvaluationManagement(this);
		}
	}
}