/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package kisti.edison.challenge.model.impl;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import kisti.edison.challenge.model.ChallengeEvaluationManagement;
import kisti.edison.challenge.model.ChallengeEvaluationManagementModel;
import kisti.edison.challenge.model.ChallengeEvaluationManagementSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

/**
 * The base model implementation for the ChallengeEvaluationManagement service. Represents a row in the &quot;challenge_ChallengeEvaluationManagement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link kisti.edison.challenge.model.ChallengeEvaluationManagementModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ChallengeEvaluationManagementImpl}.
 * </p>
 *
 * @author KYJ
 * @see ChallengeEvaluationManagementImpl
 * @see kisti.edison.challenge.model.ChallengeEvaluationManagement
 * @see kisti.edison.challenge.model.ChallengeEvaluationManagementModel
 * @generated
 */
@JSON(strict = true)
public class ChallengeEvaluationManagementModelImpl extends BaseModelImpl<ChallengeEvaluationManagement>
	implements ChallengeEvaluationManagementModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a challenge evaluation management model instance should use the {@link kisti.edison.challenge.model.ChallengeEvaluationManagement} interface instead.
	 */
	public static final String TABLE_NAME = "challenge_ChallengeEvaluationManagement";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "challengeEvaluationManagementId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "status", Types.INTEGER },
			{ "statusByUserId", Types.BIGINT },
			{ "statusByUserName", Types.VARCHAR },
			{ "statusDate", Types.TIMESTAMP },
			{ "assessmentItem", Types.VARCHAR },
			{ "distribution", Types.DOUBLE },
			{ "childChallengeId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table challenge_ChallengeEvaluationManagement (uuid_ VARCHAR(75) null,challengeEvaluationManagementId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,assessmentItem STRING null,distribution DOUBLE,childChallengeId LONG)";
	public static final String TABLE_SQL_DROP = "drop table challenge_ChallengeEvaluationManagement";
	public static final String ORDER_BY_JPQL = " ORDER BY challengeEvaluationManagement.challengeEvaluationManagementId ASC, challengeEvaluationManagement.createDate ASC";
	public static final String ORDER_BY_SQL = " ORDER BY challenge_ChallengeEvaluationManagement.challengeEvaluationManagementId ASC, challenge_ChallengeEvaluationManagement.createDate ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.kisti.edison.challenge.model.ChallengeEvaluationManagement"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.kisti.edison.challenge.model.ChallengeEvaluationManagement"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.kisti.edison.challenge.model.ChallengeEvaluationManagement"),
			true);
	public static long CHILDCHALLENGEID_COLUMN_BITMASK = 1L;
	public static long COMPANYID_COLUMN_BITMASK = 2L;
	public static long GROUPID_COLUMN_BITMASK = 4L;
	public static long UUID_COLUMN_BITMASK = 8L;
	public static long CHALLENGEEVALUATIONMANAGEMENTID_COLUMN_BITMASK = 16L;
	public static long CREATEDATE_COLUMN_BITMASK = 32L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ChallengeEvaluationManagement toModel(
		ChallengeEvaluationManagementSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ChallengeEvaluationManagement model = new ChallengeEvaluationManagementImpl();

		model.setUuid(soapModel.getUuid());
		model.setChallengeEvaluationManagementId(soapModel.getChallengeEvaluationManagementId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setAssessmentItem(soapModel.getAssessmentItem());
		model.setDistribution(soapModel.getDistribution());
		model.setChildChallengeId(soapModel.getChildChallengeId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ChallengeEvaluationManagement> toModels(
		ChallengeEvaluationManagementSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ChallengeEvaluationManagement> models = new ArrayList<ChallengeEvaluationManagement>(soapModels.length);

		for (ChallengeEvaluationManagementSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.kisti.edison.challenge.model.ChallengeEvaluationManagement"));

	public ChallengeEvaluationManagementModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _challengeEvaluationManagementId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setChallengeEvaluationManagementId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _challengeEvaluationManagementId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ChallengeEvaluationManagement.class;
	}

	@Override
	public String getModelClassName() {
		return ChallengeEvaluationManagement.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("challengeEvaluationManagementId",
			getChallengeEvaluationManagementId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("status", getStatus());
		attributes.put("statusByUserId", getStatusByUserId());
		attributes.put("statusByUserName", getStatusByUserName());
		attributes.put("statusDate", getStatusDate());
		attributes.put("assessmentItem", getAssessmentItem());
		attributes.put("distribution", getDistribution());
		attributes.put("childChallengeId", getChildChallengeId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long challengeEvaluationManagementId = (Long)attributes.get(
				"challengeEvaluationManagementId");

		if (challengeEvaluationManagementId != null) {
			setChallengeEvaluationManagementId(challengeEvaluationManagementId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Long statusByUserId = (Long)attributes.get("statusByUserId");

		if (statusByUserId != null) {
			setStatusByUserId(statusByUserId);
		}

		String statusByUserName = (String)attributes.get("statusByUserName");

		if (statusByUserName != null) {
			setStatusByUserName(statusByUserName);
		}

		Date statusDate = (Date)attributes.get("statusDate");

		if (statusDate != null) {
			setStatusDate(statusDate);
		}

		String assessmentItem = (String)attributes.get("assessmentItem");

		if (assessmentItem != null) {
			setAssessmentItem(assessmentItem);
		}

		Double distribution = (Double)attributes.get("distribution");

		if (distribution != null) {
			setDistribution(distribution);
		}

		Long childChallengeId = (Long)attributes.get("childChallengeId");

		if (childChallengeId != null) {
			setChildChallengeId(childChallengeId);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getChallengeEvaluationManagementId() {
		return _challengeEvaluationManagementId;
	}

	@Override
	public void setChallengeEvaluationManagementId(
		long challengeEvaluationManagementId) {
		_columnBitmask = -1L;

		_challengeEvaluationManagementId = challengeEvaluationManagementId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getStatusByUserId(), "uuid",
			_statusByUserUuid);
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
		_statusByUserUuid = statusByUserUuid;
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return StringPool.BLANK;
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getAssessmentItem() {
		if (_assessmentItem == null) {
			return StringPool.BLANK;
		}
		else {
			return _assessmentItem;
		}
	}

	@Override
	public String getAssessmentItem(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getAssessmentItem(languageId);
	}

	@Override
	public String getAssessmentItem(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getAssessmentItem(languageId, useDefault);
	}

	@Override
	public String getAssessmentItem(String languageId) {
		return LocalizationUtil.getLocalization(getAssessmentItem(), languageId);
	}

	@Override
	public String getAssessmentItem(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getAssessmentItem(),
			languageId, useDefault);
	}

	@Override
	public String getAssessmentItemCurrentLanguageId() {
		return _assessmentItemCurrentLanguageId;
	}

	@JSON
	@Override
	public String getAssessmentItemCurrentValue() {
		Locale locale = getLocale(_assessmentItemCurrentLanguageId);

		return getAssessmentItem(locale);
	}

	@Override
	public Map<Locale, String> getAssessmentItemMap() {
		return LocalizationUtil.getLocalizationMap(getAssessmentItem());
	}

	@Override
	public void setAssessmentItem(String assessmentItem) {
		_assessmentItem = assessmentItem;
	}

	@Override
	public void setAssessmentItem(String assessmentItem, Locale locale) {
		setAssessmentItem(assessmentItem, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setAssessmentItem(String assessmentItem, Locale locale,
		Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(assessmentItem)) {
			setAssessmentItem(LocalizationUtil.updateLocalization(
					getAssessmentItem(), "AssessmentItem", assessmentItem,
					languageId, defaultLanguageId));
		}
		else {
			setAssessmentItem(LocalizationUtil.removeLocalization(
					getAssessmentItem(), "AssessmentItem", languageId));
		}
	}

	@Override
	public void setAssessmentItemCurrentLanguageId(String languageId) {
		_assessmentItemCurrentLanguageId = languageId;
	}

	@Override
	public void setAssessmentItemMap(Map<Locale, String> assessmentItemMap) {
		setAssessmentItemMap(assessmentItemMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setAssessmentItemMap(Map<Locale, String> assessmentItemMap,
		Locale defaultLocale) {
		if (assessmentItemMap == null) {
			return;
		}

		setAssessmentItem(LocalizationUtil.updateLocalization(
				assessmentItemMap, getAssessmentItem(), "AssessmentItem",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public double getDistribution() {
		return _distribution;
	}

	@Override
	public void setDistribution(double distribution) {
		_distribution = distribution;
	}

	@JSON
	@Override
	public long getChildChallengeId() {
		return _childChallengeId;
	}

	@Override
	public void setChildChallengeId(long childChallengeId) {
		_columnBitmask |= CHILDCHALLENGEID_COLUMN_BITMASK;

		if (!_setOriginalChildChallengeId) {
			_setOriginalChildChallengeId = true;

			_originalChildChallengeId = _childChallengeId;
		}

		_childChallengeId = childChallengeId;
	}

	public long getOriginalChildChallengeId() {
		return _originalChildChallengeId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				ChallengeEvaluationManagement.class.getName()));
	}

	/**
	 * @deprecated As of 6.1.0, replaced by {@link #isApproved}
	 */
	@Override
	public boolean getApproved() {
		return isApproved();
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ChallengeEvaluationManagement.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> assessmentItemMap = getAssessmentItemMap();

		for (Map.Entry<Locale, String> entry : assessmentItemMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getAssessmentItem();

		if (xml == null) {
			return StringPool.BLANK;
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		prepareLocalizedFieldsForImport(null);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {
		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String assessmentItem = getAssessmentItem(defaultLocale);

		if (Validator.isNull(assessmentItem)) {
			setAssessmentItem(getAssessmentItem(modelDefaultLanguageId),
				defaultLocale);
		}
		else {
			setAssessmentItem(getAssessmentItem(defaultLocale), defaultLocale,
				defaultLocale);
		}
	}

	@Override
	public ChallengeEvaluationManagement toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ChallengeEvaluationManagement)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ChallengeEvaluationManagementImpl challengeEvaluationManagementImpl = new ChallengeEvaluationManagementImpl();

		challengeEvaluationManagementImpl.setUuid(getUuid());
		challengeEvaluationManagementImpl.setChallengeEvaluationManagementId(getChallengeEvaluationManagementId());
		challengeEvaluationManagementImpl.setGroupId(getGroupId());
		challengeEvaluationManagementImpl.setCompanyId(getCompanyId());
		challengeEvaluationManagementImpl.setUserId(getUserId());
		challengeEvaluationManagementImpl.setUserName(getUserName());
		challengeEvaluationManagementImpl.setCreateDate(getCreateDate());
		challengeEvaluationManagementImpl.setModifiedDate(getModifiedDate());
		challengeEvaluationManagementImpl.setStatus(getStatus());
		challengeEvaluationManagementImpl.setStatusByUserId(getStatusByUserId());
		challengeEvaluationManagementImpl.setStatusByUserName(getStatusByUserName());
		challengeEvaluationManagementImpl.setStatusDate(getStatusDate());
		challengeEvaluationManagementImpl.setAssessmentItem(getAssessmentItem());
		challengeEvaluationManagementImpl.setDistribution(getDistribution());
		challengeEvaluationManagementImpl.setChildChallengeId(getChildChallengeId());

		challengeEvaluationManagementImpl.resetOriginalValues();

		return challengeEvaluationManagementImpl;
	}

	@Override
	public int compareTo(
		ChallengeEvaluationManagement challengeEvaluationManagement) {
		int value = 0;

		if (getChallengeEvaluationManagementId() < challengeEvaluationManagement.getChallengeEvaluationManagementId()) {
			value = -1;
		}
		else if (getChallengeEvaluationManagementId() > challengeEvaluationManagement.getChallengeEvaluationManagementId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		value = DateUtil.compareTo(getCreateDate(),
				challengeEvaluationManagement.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ChallengeEvaluationManagement)) {
			return false;
		}

		ChallengeEvaluationManagement challengeEvaluationManagement = (ChallengeEvaluationManagement)obj;

		long primaryKey = challengeEvaluationManagement.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ChallengeEvaluationManagementModelImpl challengeEvaluationManagementModelImpl =
			this;

		challengeEvaluationManagementModelImpl._originalUuid = challengeEvaluationManagementModelImpl._uuid;

		challengeEvaluationManagementModelImpl._originalGroupId = challengeEvaluationManagementModelImpl._groupId;

		challengeEvaluationManagementModelImpl._setOriginalGroupId = false;

		challengeEvaluationManagementModelImpl._originalCompanyId = challengeEvaluationManagementModelImpl._companyId;

		challengeEvaluationManagementModelImpl._setOriginalCompanyId = false;

		challengeEvaluationManagementModelImpl._originalChildChallengeId = challengeEvaluationManagementModelImpl._childChallengeId;

		challengeEvaluationManagementModelImpl._setOriginalChildChallengeId = false;

		challengeEvaluationManagementModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ChallengeEvaluationManagement> toCacheModel() {
		ChallengeEvaluationManagementCacheModel challengeEvaluationManagementCacheModel =
			new ChallengeEvaluationManagementCacheModel();

		challengeEvaluationManagementCacheModel.uuid = getUuid();

		String uuid = challengeEvaluationManagementCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			challengeEvaluationManagementCacheModel.uuid = null;
		}

		challengeEvaluationManagementCacheModel.challengeEvaluationManagementId = getChallengeEvaluationManagementId();

		challengeEvaluationManagementCacheModel.groupId = getGroupId();

		challengeEvaluationManagementCacheModel.companyId = getCompanyId();

		challengeEvaluationManagementCacheModel.userId = getUserId();

		challengeEvaluationManagementCacheModel.userName = getUserName();

		String userName = challengeEvaluationManagementCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			challengeEvaluationManagementCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			challengeEvaluationManagementCacheModel.createDate = createDate.getTime();
		}
		else {
			challengeEvaluationManagementCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			challengeEvaluationManagementCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			challengeEvaluationManagementCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		challengeEvaluationManagementCacheModel.status = getStatus();

		challengeEvaluationManagementCacheModel.statusByUserId = getStatusByUserId();

		challengeEvaluationManagementCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = challengeEvaluationManagementCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			challengeEvaluationManagementCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			challengeEvaluationManagementCacheModel.statusDate = statusDate.getTime();
		}
		else {
			challengeEvaluationManagementCacheModel.statusDate = Long.MIN_VALUE;
		}

		challengeEvaluationManagementCacheModel.assessmentItem = getAssessmentItem();

		String assessmentItem = challengeEvaluationManagementCacheModel.assessmentItem;

		if ((assessmentItem != null) && (assessmentItem.length() == 0)) {
			challengeEvaluationManagementCacheModel.assessmentItem = null;
		}

		challengeEvaluationManagementCacheModel.distribution = getDistribution();

		challengeEvaluationManagementCacheModel.childChallengeId = getChildChallengeId();

		return challengeEvaluationManagementCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(31);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", challengeEvaluationManagementId=");
		sb.append(getChallengeEvaluationManagementId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", statusByUserId=");
		sb.append(getStatusByUserId());
		sb.append(", statusByUserName=");
		sb.append(getStatusByUserName());
		sb.append(", statusDate=");
		sb.append(getStatusDate());
		sb.append(", assessmentItem=");
		sb.append(getAssessmentItem());
		sb.append(", distribution=");
		sb.append(getDistribution());
		sb.append(", childChallengeId=");
		sb.append(getChildChallengeId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(49);

		sb.append("<model><model-name>");
		sb.append("kisti.edison.challenge.model.ChallengeEvaluationManagement");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>challengeEvaluationManagementId</column-name><column-value><![CDATA[");
		sb.append(getChallengeEvaluationManagementId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserId</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserName</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusDate</column-name><column-value><![CDATA[");
		sb.append(getStatusDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>assessmentItem</column-name><column-value><![CDATA[");
		sb.append(getAssessmentItem());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>distribution</column-name><column-value><![CDATA[");
		sb.append(getDistribution());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>childChallengeId</column-name><column-value><![CDATA[");
		sb.append(getChildChallengeId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ChallengeEvaluationManagement.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ChallengeEvaluationManagement.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _challengeEvaluationManagementId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserUuid;
	private String _statusByUserName;
	private Date _statusDate;
	private String _assessmentItem;
	private String _assessmentItemCurrentLanguageId;
	private double _distribution;
	private long _childChallengeId;
	private long _originalChildChallengeId;
	private boolean _setOriginalChildChallengeId;
	private long _columnBitmask;
	private ChallengeEvaluationManagement _escapedModel;
}