/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package edison.challenge.service.builder.model.impl;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import edison.challenge.service.builder.model.ChallengeMember;
import edison.challenge.service.builder.model.ChallengeMemberModel;
import edison.challenge.service.builder.model.ChallengeMemberSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

/**
 * The base model implementation for the ChallengeMember service. Represents a row in the &quot;edison_ChallengeMember&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link edison.challenge.service.builder.model.ChallengeMemberModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ChallengeMemberImpl}.
 * </p>
 *
 * @author kyj
 * @see ChallengeMemberImpl
 * @see edison.challenge.service.builder.model.ChallengeMember
 * @see edison.challenge.service.builder.model.ChallengeMemberModel
 * @generated
 */
@JSON(strict = true)
public class ChallengeMemberModelImpl extends BaseModelImpl<ChallengeMember>
	implements ChallengeMemberModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a challenge member model instance should use the {@link edison.challenge.service.builder.model.ChallengeMember} interface instead.
	 */
	public static final String TABLE_NAME = "edison_ChallengeMember";
	public static final Object[][] TABLE_COLUMNS = {
			{ "chMemberid", Types.BIGINT },
			{ "fullName", Types.VARCHAR },
			{ "screenName", Types.VARCHAR },
			{ "email", Types.VARCHAR },
			{ "leader", Types.BOOLEAN },
			{ "falculty", Types.VARCHAR },
			{ "major", Types.VARCHAR },
			{ "grade", Types.VARCHAR },
			{ "chTeamid", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table edison_ChallengeMember (chMemberid LONG not null primary key,fullName STRING null,screenName STRING null,email VARCHAR(75) null,leader BOOLEAN,falculty STRING null,major STRING null,grade VARCHAR(75) null,chTeamid LONG)";
	public static final String TABLE_SQL_DROP = "drop table edison_ChallengeMember";
	public static final String ORDER_BY_JPQL = " ORDER BY challengeMember.chTeamid ASC";
	public static final String ORDER_BY_SQL = " ORDER BY edison_ChallengeMember.chTeamid ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.edison.challenge.service.builder.model.ChallengeMember"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.edison.challenge.service.builder.model.ChallengeMember"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.edison.challenge.service.builder.model.ChallengeMember"),
			true);
	public static long CHTEAMID_COLUMN_BITMASK = 1L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ChallengeMember toModel(ChallengeMemberSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ChallengeMember model = new ChallengeMemberImpl();

		model.setChMemberid(soapModel.getChMemberid());
		model.setFullName(soapModel.getFullName());
		model.setScreenName(soapModel.getScreenName());
		model.setEmail(soapModel.getEmail());
		model.setLeader(soapModel.getLeader());
		model.setFalculty(soapModel.getFalculty());
		model.setMajor(soapModel.getMajor());
		model.setGrade(soapModel.getGrade());
		model.setChTeamid(soapModel.getChTeamid());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ChallengeMember> toModels(
		ChallengeMemberSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ChallengeMember> models = new ArrayList<ChallengeMember>(soapModels.length);

		for (ChallengeMemberSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.edison.challenge.service.builder.model.ChallengeMember"));

	public ChallengeMemberModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _chMemberid;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setChMemberid(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _chMemberid;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ChallengeMember.class;
	}

	@Override
	public String getModelClassName() {
		return ChallengeMember.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("chMemberid", getChMemberid());
		attributes.put("fullName", getFullName());
		attributes.put("screenName", getScreenName());
		attributes.put("email", getEmail());
		attributes.put("leader", getLeader());
		attributes.put("falculty", getFalculty());
		attributes.put("major", getMajor());
		attributes.put("grade", getGrade());
		attributes.put("chTeamid", getChTeamid());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long chMemberid = (Long)attributes.get("chMemberid");

		if (chMemberid != null) {
			setChMemberid(chMemberid);
		}

		String fullName = (String)attributes.get("fullName");

		if (fullName != null) {
			setFullName(fullName);
		}

		String screenName = (String)attributes.get("screenName");

		if (screenName != null) {
			setScreenName(screenName);
		}

		String email = (String)attributes.get("email");

		if (email != null) {
			setEmail(email);
		}

		Boolean leader = (Boolean)attributes.get("leader");

		if (leader != null) {
			setLeader(leader);
		}

		String falculty = (String)attributes.get("falculty");

		if (falculty != null) {
			setFalculty(falculty);
		}

		String major = (String)attributes.get("major");

		if (major != null) {
			setMajor(major);
		}

		String grade = (String)attributes.get("grade");

		if (grade != null) {
			setGrade(grade);
		}

		Long chTeamid = (Long)attributes.get("chTeamid");

		if (chTeamid != null) {
			setChTeamid(chTeamid);
		}
	}

	@JSON
	@Override
	public long getChMemberid() {
		return _chMemberid;
	}

	@Override
	public void setChMemberid(long chMemberid) {
		_chMemberid = chMemberid;
	}

	@JSON
	@Override
	public String getFullName() {
		if (_fullName == null) {
			return StringPool.BLANK;
		}
		else {
			return _fullName;
		}
	}

	@Override
	public String getFullName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getFullName(languageId);
	}

	@Override
	public String getFullName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getFullName(languageId, useDefault);
	}

	@Override
	public String getFullName(String languageId) {
		return LocalizationUtil.getLocalization(getFullName(), languageId);
	}

	@Override
	public String getFullName(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getFullName(), languageId,
			useDefault);
	}

	@Override
	public String getFullNameCurrentLanguageId() {
		return _fullNameCurrentLanguageId;
	}

	@JSON
	@Override
	public String getFullNameCurrentValue() {
		Locale locale = getLocale(_fullNameCurrentLanguageId);

		return getFullName(locale);
	}

	@Override
	public Map<Locale, String> getFullNameMap() {
		return LocalizationUtil.getLocalizationMap(getFullName());
	}

	@Override
	public void setFullName(String fullName) {
		_fullName = fullName;
	}

	@Override
	public void setFullName(String fullName, Locale locale) {
		setFullName(fullName, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setFullName(String fullName, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(fullName)) {
			setFullName(LocalizationUtil.updateLocalization(getFullName(),
					"FullName", fullName, languageId, defaultLanguageId));
		}
		else {
			setFullName(LocalizationUtil.removeLocalization(getFullName(),
					"FullName", languageId));
		}
	}

	@Override
	public void setFullNameCurrentLanguageId(String languageId) {
		_fullNameCurrentLanguageId = languageId;
	}

	@Override
	public void setFullNameMap(Map<Locale, String> fullNameMap) {
		setFullNameMap(fullNameMap, LocaleUtil.getDefault());
	}

	@Override
	public void setFullNameMap(Map<Locale, String> fullNameMap,
		Locale defaultLocale) {
		if (fullNameMap == null) {
			return;
		}

		setFullName(LocalizationUtil.updateLocalization(fullNameMap,
				getFullName(), "FullName",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getScreenName() {
		if (_screenName == null) {
			return StringPool.BLANK;
		}
		else {
			return _screenName;
		}
	}

	@Override
	public String getScreenName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getScreenName(languageId);
	}

	@Override
	public String getScreenName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getScreenName(languageId, useDefault);
	}

	@Override
	public String getScreenName(String languageId) {
		return LocalizationUtil.getLocalization(getScreenName(), languageId);
	}

	@Override
	public String getScreenName(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getScreenName(), languageId,
			useDefault);
	}

	@Override
	public String getScreenNameCurrentLanguageId() {
		return _screenNameCurrentLanguageId;
	}

	@JSON
	@Override
	public String getScreenNameCurrentValue() {
		Locale locale = getLocale(_screenNameCurrentLanguageId);

		return getScreenName(locale);
	}

	@Override
	public Map<Locale, String> getScreenNameMap() {
		return LocalizationUtil.getLocalizationMap(getScreenName());
	}

	@Override
	public void setScreenName(String screenName) {
		_screenName = screenName;
	}

	@Override
	public void setScreenName(String screenName, Locale locale) {
		setScreenName(screenName, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setScreenName(String screenName, Locale locale,
		Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(screenName)) {
			setScreenName(LocalizationUtil.updateLocalization(getScreenName(),
					"ScreenName", screenName, languageId, defaultLanguageId));
		}
		else {
			setScreenName(LocalizationUtil.removeLocalization(getScreenName(),
					"ScreenName", languageId));
		}
	}

	@Override
	public void setScreenNameCurrentLanguageId(String languageId) {
		_screenNameCurrentLanguageId = languageId;
	}

	@Override
	public void setScreenNameMap(Map<Locale, String> screenNameMap) {
		setScreenNameMap(screenNameMap, LocaleUtil.getDefault());
	}

	@Override
	public void setScreenNameMap(Map<Locale, String> screenNameMap,
		Locale defaultLocale) {
		if (screenNameMap == null) {
			return;
		}

		setScreenName(LocalizationUtil.updateLocalization(screenNameMap,
				getScreenName(), "ScreenName",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return StringPool.BLANK;
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		_email = email;
	}

	@JSON
	@Override
	public boolean getLeader() {
		return _leader;
	}

	@Override
	public boolean isLeader() {
		return _leader;
	}

	@Override
	public void setLeader(boolean leader) {
		_leader = leader;
	}

	@JSON
	@Override
	public String getFalculty() {
		if (_falculty == null) {
			return StringPool.BLANK;
		}
		else {
			return _falculty;
		}
	}

	@Override
	public String getFalculty(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getFalculty(languageId);
	}

	@Override
	public String getFalculty(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getFalculty(languageId, useDefault);
	}

	@Override
	public String getFalculty(String languageId) {
		return LocalizationUtil.getLocalization(getFalculty(), languageId);
	}

	@Override
	public String getFalculty(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getFalculty(), languageId,
			useDefault);
	}

	@Override
	public String getFalcultyCurrentLanguageId() {
		return _falcultyCurrentLanguageId;
	}

	@JSON
	@Override
	public String getFalcultyCurrentValue() {
		Locale locale = getLocale(_falcultyCurrentLanguageId);

		return getFalculty(locale);
	}

	@Override
	public Map<Locale, String> getFalcultyMap() {
		return LocalizationUtil.getLocalizationMap(getFalculty());
	}

	@Override
	public void setFalculty(String falculty) {
		_falculty = falculty;
	}

	@Override
	public void setFalculty(String falculty, Locale locale) {
		setFalculty(falculty, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setFalculty(String falculty, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(falculty)) {
			setFalculty(LocalizationUtil.updateLocalization(getFalculty(),
					"Falculty", falculty, languageId, defaultLanguageId));
		}
		else {
			setFalculty(LocalizationUtil.removeLocalization(getFalculty(),
					"Falculty", languageId));
		}
	}

	@Override
	public void setFalcultyCurrentLanguageId(String languageId) {
		_falcultyCurrentLanguageId = languageId;
	}

	@Override
	public void setFalcultyMap(Map<Locale, String> falcultyMap) {
		setFalcultyMap(falcultyMap, LocaleUtil.getDefault());
	}

	@Override
	public void setFalcultyMap(Map<Locale, String> falcultyMap,
		Locale defaultLocale) {
		if (falcultyMap == null) {
			return;
		}

		setFalculty(LocalizationUtil.updateLocalization(falcultyMap,
				getFalculty(), "Falculty",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getMajor() {
		if (_major == null) {
			return StringPool.BLANK;
		}
		else {
			return _major;
		}
	}

	@Override
	public String getMajor(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getMajor(languageId);
	}

	@Override
	public String getMajor(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getMajor(languageId, useDefault);
	}

	@Override
	public String getMajor(String languageId) {
		return LocalizationUtil.getLocalization(getMajor(), languageId);
	}

	@Override
	public String getMajor(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getMajor(), languageId,
			useDefault);
	}

	@Override
	public String getMajorCurrentLanguageId() {
		return _majorCurrentLanguageId;
	}

	@JSON
	@Override
	public String getMajorCurrentValue() {
		Locale locale = getLocale(_majorCurrentLanguageId);

		return getMajor(locale);
	}

	@Override
	public Map<Locale, String> getMajorMap() {
		return LocalizationUtil.getLocalizationMap(getMajor());
	}

	@Override
	public void setMajor(String major) {
		_major = major;
	}

	@Override
	public void setMajor(String major, Locale locale) {
		setMajor(major, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setMajor(String major, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(major)) {
			setMajor(LocalizationUtil.updateLocalization(getMajor(), "Major",
					major, languageId, defaultLanguageId));
		}
		else {
			setMajor(LocalizationUtil.removeLocalization(getMajor(), "Major",
					languageId));
		}
	}

	@Override
	public void setMajorCurrentLanguageId(String languageId) {
		_majorCurrentLanguageId = languageId;
	}

	@Override
	public void setMajorMap(Map<Locale, String> majorMap) {
		setMajorMap(majorMap, LocaleUtil.getDefault());
	}

	@Override
	public void setMajorMap(Map<Locale, String> majorMap, Locale defaultLocale) {
		if (majorMap == null) {
			return;
		}

		setMajor(LocalizationUtil.updateLocalization(majorMap, getMajor(),
				"Major", LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getGrade() {
		if (_grade == null) {
			return StringPool.BLANK;
		}
		else {
			return _grade;
		}
	}

	@Override
	public void setGrade(String grade) {
		_grade = grade;
	}

	@JSON
	@Override
	public long getChTeamid() {
		return _chTeamid;
	}

	@Override
	public void setChTeamid(long chTeamid) {
		_columnBitmask = -1L;

		if (!_setOriginalChTeamid) {
			_setOriginalChTeamid = true;

			_originalChTeamid = _chTeamid;
		}

		_chTeamid = chTeamid;
	}

	public long getOriginalChTeamid() {
		return _originalChTeamid;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ChallengeMember.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> fullNameMap = getFullNameMap();

		for (Map.Entry<Locale, String> entry : fullNameMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> screenNameMap = getScreenNameMap();

		for (Map.Entry<Locale, String> entry : screenNameMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> falcultyMap = getFalcultyMap();

		for (Map.Entry<Locale, String> entry : falcultyMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> majorMap = getMajorMap();

		for (Map.Entry<Locale, String> entry : majorMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getFullName();

		if (xml == null) {
			return StringPool.BLANK;
		}

		Locale defaultLocale = LocaleUtil.getDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		prepareLocalizedFieldsForImport(null);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {
		Locale defaultLocale = LocaleUtil.getDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String fullName = getFullName(defaultLocale);

		if (Validator.isNull(fullName)) {
			setFullName(getFullName(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setFullName(getFullName(defaultLocale), defaultLocale, defaultLocale);
		}

		String screenName = getScreenName(defaultLocale);

		if (Validator.isNull(screenName)) {
			setScreenName(getScreenName(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setScreenName(getScreenName(defaultLocale), defaultLocale,
				defaultLocale);
		}

		String falculty = getFalculty(defaultLocale);

		if (Validator.isNull(falculty)) {
			setFalculty(getFalculty(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setFalculty(getFalculty(defaultLocale), defaultLocale, defaultLocale);
		}

		String major = getMajor(defaultLocale);

		if (Validator.isNull(major)) {
			setMajor(getMajor(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setMajor(getMajor(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public ChallengeMember toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ChallengeMember)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ChallengeMemberImpl challengeMemberImpl = new ChallengeMemberImpl();

		challengeMemberImpl.setChMemberid(getChMemberid());
		challengeMemberImpl.setFullName(getFullName());
		challengeMemberImpl.setScreenName(getScreenName());
		challengeMemberImpl.setEmail(getEmail());
		challengeMemberImpl.setLeader(getLeader());
		challengeMemberImpl.setFalculty(getFalculty());
		challengeMemberImpl.setMajor(getMajor());
		challengeMemberImpl.setGrade(getGrade());
		challengeMemberImpl.setChTeamid(getChTeamid());

		challengeMemberImpl.resetOriginalValues();

		return challengeMemberImpl;
	}

	@Override
	public int compareTo(ChallengeMember challengeMember) {
		int value = 0;

		if (getChTeamid() < challengeMember.getChTeamid()) {
			value = -1;
		}
		else if (getChTeamid() > challengeMember.getChTeamid()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ChallengeMember)) {
			return false;
		}

		ChallengeMember challengeMember = (ChallengeMember)obj;

		long primaryKey = challengeMember.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ChallengeMemberModelImpl challengeMemberModelImpl = this;

		challengeMemberModelImpl._originalChTeamid = challengeMemberModelImpl._chTeamid;

		challengeMemberModelImpl._setOriginalChTeamid = false;

		challengeMemberModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ChallengeMember> toCacheModel() {
		ChallengeMemberCacheModel challengeMemberCacheModel = new ChallengeMemberCacheModel();

		challengeMemberCacheModel.chMemberid = getChMemberid();

		challengeMemberCacheModel.fullName = getFullName();

		String fullName = challengeMemberCacheModel.fullName;

		if ((fullName != null) && (fullName.length() == 0)) {
			challengeMemberCacheModel.fullName = null;
		}

		challengeMemberCacheModel.screenName = getScreenName();

		String screenName = challengeMemberCacheModel.screenName;

		if ((screenName != null) && (screenName.length() == 0)) {
			challengeMemberCacheModel.screenName = null;
		}

		challengeMemberCacheModel.email = getEmail();

		String email = challengeMemberCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			challengeMemberCacheModel.email = null;
		}

		challengeMemberCacheModel.leader = getLeader();

		challengeMemberCacheModel.falculty = getFalculty();

		String falculty = challengeMemberCacheModel.falculty;

		if ((falculty != null) && (falculty.length() == 0)) {
			challengeMemberCacheModel.falculty = null;
		}

		challengeMemberCacheModel.major = getMajor();

		String major = challengeMemberCacheModel.major;

		if ((major != null) && (major.length() == 0)) {
			challengeMemberCacheModel.major = null;
		}

		challengeMemberCacheModel.grade = getGrade();

		String grade = challengeMemberCacheModel.grade;

		if ((grade != null) && (grade.length() == 0)) {
			challengeMemberCacheModel.grade = null;
		}

		challengeMemberCacheModel.chTeamid = getChTeamid();

		return challengeMemberCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{chMemberid=");
		sb.append(getChMemberid());
		sb.append(", fullName=");
		sb.append(getFullName());
		sb.append(", screenName=");
		sb.append(getScreenName());
		sb.append(", email=");
		sb.append(getEmail());
		sb.append(", leader=");
		sb.append(getLeader());
		sb.append(", falculty=");
		sb.append(getFalculty());
		sb.append(", major=");
		sb.append(getMajor());
		sb.append(", grade=");
		sb.append(getGrade());
		sb.append(", chTeamid=");
		sb.append(getChTeamid());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("edison.challenge.service.builder.model.ChallengeMember");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>chMemberid</column-name><column-value><![CDATA[");
		sb.append(getChMemberid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fullName</column-name><column-value><![CDATA[");
		sb.append(getFullName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>screenName</column-name><column-value><![CDATA[");
		sb.append(getScreenName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>email</column-name><column-value><![CDATA[");
		sb.append(getEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>leader</column-name><column-value><![CDATA[");
		sb.append(getLeader());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>falculty</column-name><column-value><![CDATA[");
		sb.append(getFalculty());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>major</column-name><column-value><![CDATA[");
		sb.append(getMajor());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>grade</column-name><column-value><![CDATA[");
		sb.append(getGrade());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chTeamid</column-name><column-value><![CDATA[");
		sb.append(getChTeamid());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ChallengeMember.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ChallengeMember.class
		};
	private long _chMemberid;
	private String _fullName;
	private String _fullNameCurrentLanguageId;
	private String _screenName;
	private String _screenNameCurrentLanguageId;
	private String _email;
	private boolean _leader;
	private String _falculty;
	private String _falcultyCurrentLanguageId;
	private String _major;
	private String _majorCurrentLanguageId;
	private String _grade;
	private long _chTeamid;
	private long _originalChTeamid;
	private boolean _setOriginalChTeamid;
	private long _columnBitmask;
	private ChallengeMember _escapedModel;
}