/**
 * Copyright (c) 2016-present EDISON, KISTI. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.kisti.edison.bestsimulation.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import org.kisti.edison.bestsimulation.model.UniversityExecute;
import org.kisti.edison.bestsimulation.model.UniversityExecuteModel;
import org.kisti.edison.bestsimulation.model.UniversityExecuteSoap;
import org.kisti.edison.bestsimulation.service.persistence.UniversityExecutePK;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the UniversityExecute service. Represents a row in the &quot;EDSIM_UniversityExecute&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.kisti.edison.bestsimulation.model.UniversityExecuteModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UniversityExecuteImpl}.
 * </p>
 *
 * @author EDISON
 * @see UniversityExecuteImpl
 * @see org.kisti.edison.bestsimulation.model.UniversityExecute
 * @see org.kisti.edison.bestsimulation.model.UniversityExecuteModel
 * @generated
 */
@JSON(strict = true)
public class UniversityExecuteModelImpl extends BaseModelImpl<UniversityExecute>
	implements UniversityExecuteModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a university execute model instance should use the {@link org.kisti.edison.bestsimulation.model.UniversityExecute} interface instead.
	 */
	public static final String TABLE_NAME = "EDSIM_UniversityExecute";
	public static final Object[][] TABLE_COLUMNS = {
			{ "executeDate", Types.VARCHAR },
			{ "universityField", Types.BIGINT },
			{ "userCnt", Types.BIGINT },
			{ "avgExeTime", Types.BIGINT },
			{ "exeCnt", Types.BIGINT },
			{ "cpuTime", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table EDSIM_UniversityExecute (executeDate VARCHAR(75) not null,universityField LONG not null,userCnt LONG,avgExeTime LONG,exeCnt LONG,cpuTime LONG,primary key (executeDate, universityField))";
	public static final String TABLE_SQL_DROP = "drop table EDSIM_UniversityExecute";
	public static final String ORDER_BY_JPQL = " ORDER BY universityExecute.id.executeDate ASC, universityExecute.id.universityField ASC";
	public static final String ORDER_BY_SQL = " ORDER BY EDSIM_UniversityExecute.executeDate ASC, EDSIM_UniversityExecute.universityField ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "true";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.kisti.edison.bestsimulation.model.UniversityExecute"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.kisti.edison.bestsimulation.model.UniversityExecute"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static UniversityExecute toModel(UniversityExecuteSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		UniversityExecute model = new UniversityExecuteImpl();

		model.setExecuteDate(soapModel.getExecuteDate());
		model.setUniversityField(soapModel.getUniversityField());
		model.setUserCnt(soapModel.getUserCnt());
		model.setAvgExeTime(soapModel.getAvgExeTime());
		model.setExeCnt(soapModel.getExeCnt());
		model.setCpuTime(soapModel.getCpuTime());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<UniversityExecute> toModels(
		UniversityExecuteSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<UniversityExecute> models = new ArrayList<UniversityExecute>(soapModels.length);

		for (UniversityExecuteSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.kisti.edison.bestsimulation.model.UniversityExecute"));

	public UniversityExecuteModelImpl() {
	}

	@Override
	public UniversityExecutePK getPrimaryKey() {
		return new UniversityExecutePK(_executeDate, _universityField);
	}

	@Override
	public void setPrimaryKey(UniversityExecutePK primaryKey) {
		setExecuteDate(primaryKey.executeDate);
		setUniversityField(primaryKey.universityField);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new UniversityExecutePK(_executeDate, _universityField);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((UniversityExecutePK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return UniversityExecute.class;
	}

	@Override
	public String getModelClassName() {
		return UniversityExecute.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("executeDate", getExecuteDate());
		attributes.put("universityField", getUniversityField());
		attributes.put("userCnt", getUserCnt());
		attributes.put("avgExeTime", getAvgExeTime());
		attributes.put("exeCnt", getExeCnt());
		attributes.put("cpuTime", getCpuTime());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String executeDate = (String)attributes.get("executeDate");

		if (executeDate != null) {
			setExecuteDate(executeDate);
		}

		Long universityField = (Long)attributes.get("universityField");

		if (universityField != null) {
			setUniversityField(universityField);
		}

		Long userCnt = (Long)attributes.get("userCnt");

		if (userCnt != null) {
			setUserCnt(userCnt);
		}

		Long avgExeTime = (Long)attributes.get("avgExeTime");

		if (avgExeTime != null) {
			setAvgExeTime(avgExeTime);
		}

		Long exeCnt = (Long)attributes.get("exeCnt");

		if (exeCnt != null) {
			setExeCnt(exeCnt);
		}

		Long cpuTime = (Long)attributes.get("cpuTime");

		if (cpuTime != null) {
			setCpuTime(cpuTime);
		}
	}

	@JSON
	@Override
	public String getExecuteDate() {
		if (_executeDate == null) {
			return StringPool.BLANK;
		}
		else {
			return _executeDate;
		}
	}

	@Override
	public void setExecuteDate(String executeDate) {
		_executeDate = executeDate;
	}

	@JSON
	@Override
	public long getUniversityField() {
		return _universityField;
	}

	@Override
	public void setUniversityField(long universityField) {
		_universityField = universityField;
	}

	@JSON
	@Override
	public long getUserCnt() {
		return _userCnt;
	}

	@Override
	public void setUserCnt(long userCnt) {
		_userCnt = userCnt;
	}

	@JSON
	@Override
	public long getAvgExeTime() {
		return _avgExeTime;
	}

	@Override
	public void setAvgExeTime(long avgExeTime) {
		_avgExeTime = avgExeTime;
	}

	@JSON
	@Override
	public long getExeCnt() {
		return _exeCnt;
	}

	@Override
	public void setExeCnt(long exeCnt) {
		_exeCnt = exeCnt;
	}

	@JSON
	@Override
	public long getCpuTime() {
		return _cpuTime;
	}

	@Override
	public void setCpuTime(long cpuTime) {
		_cpuTime = cpuTime;
	}

	@Override
	public UniversityExecute toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (UniversityExecute)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UniversityExecuteImpl universityExecuteImpl = new UniversityExecuteImpl();

		universityExecuteImpl.setExecuteDate(getExecuteDate());
		universityExecuteImpl.setUniversityField(getUniversityField());
		universityExecuteImpl.setUserCnt(getUserCnt());
		universityExecuteImpl.setAvgExeTime(getAvgExeTime());
		universityExecuteImpl.setExeCnt(getExeCnt());
		universityExecuteImpl.setCpuTime(getCpuTime());

		universityExecuteImpl.resetOriginalValues();

		return universityExecuteImpl;
	}

	@Override
	public int compareTo(UniversityExecute universityExecute) {
		UniversityExecutePK primaryKey = universityExecute.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof UniversityExecute)) {
			return false;
		}

		UniversityExecute universityExecute = (UniversityExecute)obj;

		UniversityExecutePK primaryKey = universityExecute.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<UniversityExecute> toCacheModel() {
		UniversityExecuteCacheModel universityExecuteCacheModel = new UniversityExecuteCacheModel();

		universityExecuteCacheModel.executeDate = getExecuteDate();

		String executeDate = universityExecuteCacheModel.executeDate;

		if ((executeDate != null) && (executeDate.length() == 0)) {
			universityExecuteCacheModel.executeDate = null;
		}

		universityExecuteCacheModel.universityField = getUniversityField();

		universityExecuteCacheModel.userCnt = getUserCnt();

		universityExecuteCacheModel.avgExeTime = getAvgExeTime();

		universityExecuteCacheModel.exeCnt = getExeCnt();

		universityExecuteCacheModel.cpuTime = getCpuTime();

		return universityExecuteCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{executeDate=");
		sb.append(getExecuteDate());
		sb.append(", universityField=");
		sb.append(getUniversityField());
		sb.append(", userCnt=");
		sb.append(getUserCnt());
		sb.append(", avgExeTime=");
		sb.append(getAvgExeTime());
		sb.append(", exeCnt=");
		sb.append(getExeCnt());
		sb.append(", cpuTime=");
		sb.append(getCpuTime());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("org.kisti.edison.bestsimulation.model.UniversityExecute");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>executeDate</column-name><column-value><![CDATA[");
		sb.append(getExecuteDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>universityField</column-name><column-value><![CDATA[");
		sb.append(getUniversityField());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userCnt</column-name><column-value><![CDATA[");
		sb.append(getUserCnt());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>avgExeTime</column-name><column-value><![CDATA[");
		sb.append(getAvgExeTime());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>exeCnt</column-name><column-value><![CDATA[");
		sb.append(getExeCnt());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cpuTime</column-name><column-value><![CDATA[");
		sb.append(getCpuTime());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = UniversityExecute.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			UniversityExecute.class
		};
	private String _executeDate;
	private long _universityField;
	private long _userCnt;
	private long _avgExeTime;
	private long _exeCnt;
	private long _cpuTime;
	private UniversityExecute _escapedModel;
}