/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.kisti.edison.content.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import com.liferay.portlet.asset.service.persistence.AssetEntryPersistence;
import com.liferay.portlet.asset.service.persistence.AssetLinkPersistence;

import org.kisti.edison.content.model.Content;
import org.kisti.edison.content.service.ContentService;
import org.kisti.edison.content.service.persistence.AdvancedContentPersistence;
import org.kisti.edison.content.service.persistence.ContentFinder;
import org.kisti.edison.content.service.persistence.ContentPersistence;
import org.kisti.edison.content.service.persistence.GeneralContentPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the content remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link org.kisti.edison.content.service.impl.ContentServiceImpl}.
 * </p>
 *
 * @author EDISON
 * @see org.kisti.edison.content.service.impl.ContentServiceImpl
 * @see org.kisti.edison.content.service.ContentServiceUtil
 * @generated
 */
public abstract class ContentServiceBaseImpl extends BaseServiceImpl
	implements ContentService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link org.kisti.edison.content.service.ContentServiceUtil} to access the content remote service.
	 */

	/**
	 * Returns the advanced content local service.
	 *
	 * @return the advanced content local service
	 */
	public org.kisti.edison.content.service.AdvancedContentLocalService getAdvancedContentLocalService() {
		return advancedContentLocalService;
	}

	/**
	 * Sets the advanced content local service.
	 *
	 * @param advancedContentLocalService the advanced content local service
	 */
	public void setAdvancedContentLocalService(
		org.kisti.edison.content.service.AdvancedContentLocalService advancedContentLocalService) {
		this.advancedContentLocalService = advancedContentLocalService;
	}

	/**
	 * Returns the advanced content remote service.
	 *
	 * @return the advanced content remote service
	 */
	public org.kisti.edison.content.service.AdvancedContentService getAdvancedContentService() {
		return advancedContentService;
	}

	/**
	 * Sets the advanced content remote service.
	 *
	 * @param advancedContentService the advanced content remote service
	 */
	public void setAdvancedContentService(
		org.kisti.edison.content.service.AdvancedContentService advancedContentService) {
		this.advancedContentService = advancedContentService;
	}

	/**
	 * Returns the advanced content persistence.
	 *
	 * @return the advanced content persistence
	 */
	public AdvancedContentPersistence getAdvancedContentPersistence() {
		return advancedContentPersistence;
	}

	/**
	 * Sets the advanced content persistence.
	 *
	 * @param advancedContentPersistence the advanced content persistence
	 */
	public void setAdvancedContentPersistence(
		AdvancedContentPersistence advancedContentPersistence) {
		this.advancedContentPersistence = advancedContentPersistence;
	}

	/**
	 * Returns the content local service.
	 *
	 * @return the content local service
	 */
	public org.kisti.edison.content.service.ContentLocalService getContentLocalService() {
		return contentLocalService;
	}

	/**
	 * Sets the content local service.
	 *
	 * @param contentLocalService the content local service
	 */
	public void setContentLocalService(
		org.kisti.edison.content.service.ContentLocalService contentLocalService) {
		this.contentLocalService = contentLocalService;
	}

	/**
	 * Returns the content remote service.
	 *
	 * @return the content remote service
	 */
	public org.kisti.edison.content.service.ContentService getContentService() {
		return contentService;
	}

	/**
	 * Sets the content remote service.
	 *
	 * @param contentService the content remote service
	 */
	public void setContentService(
		org.kisti.edison.content.service.ContentService contentService) {
		this.contentService = contentService;
	}

	/**
	 * Returns the content persistence.
	 *
	 * @return the content persistence
	 */
	public ContentPersistence getContentPersistence() {
		return contentPersistence;
	}

	/**
	 * Sets the content persistence.
	 *
	 * @param contentPersistence the content persistence
	 */
	public void setContentPersistence(ContentPersistence contentPersistence) {
		this.contentPersistence = contentPersistence;
	}

	/**
	 * Returns the content finder.
	 *
	 * @return the content finder
	 */
	public ContentFinder getContentFinder() {
		return contentFinder;
	}

	/**
	 * Sets the content finder.
	 *
	 * @param contentFinder the content finder
	 */
	public void setContentFinder(ContentFinder contentFinder) {
		this.contentFinder = contentFinder;
	}

	/**
	 * Returns the general content local service.
	 *
	 * @return the general content local service
	 */
	public org.kisti.edison.content.service.GeneralContentLocalService getGeneralContentLocalService() {
		return generalContentLocalService;
	}

	/**
	 * Sets the general content local service.
	 *
	 * @param generalContentLocalService the general content local service
	 */
	public void setGeneralContentLocalService(
		org.kisti.edison.content.service.GeneralContentLocalService generalContentLocalService) {
		this.generalContentLocalService = generalContentLocalService;
	}

	/**
	 * Returns the general content remote service.
	 *
	 * @return the general content remote service
	 */
	public org.kisti.edison.content.service.GeneralContentService getGeneralContentService() {
		return generalContentService;
	}

	/**
	 * Sets the general content remote service.
	 *
	 * @param generalContentService the general content remote service
	 */
	public void setGeneralContentService(
		org.kisti.edison.content.service.GeneralContentService generalContentService) {
		this.generalContentService = generalContentService;
	}

	/**
	 * Returns the general content persistence.
	 *
	 * @return the general content persistence
	 */
	public GeneralContentPersistence getGeneralContentPersistence() {
		return generalContentPersistence;
	}

	/**
	 * Sets the general content persistence.
	 *
	 * @param generalContentPersistence the general content persistence
	 */
	public void setGeneralContentPersistence(
		GeneralContentPersistence generalContentPersistence) {
		this.generalContentPersistence = generalContentPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Returns the asset entry local service.
	 *
	 * @return the asset entry local service
	 */
	public com.liferay.portlet.asset.service.AssetEntryLocalService getAssetEntryLocalService() {
		return assetEntryLocalService;
	}

	/**
	 * Sets the asset entry local service.
	 *
	 * @param assetEntryLocalService the asset entry local service
	 */
	public void setAssetEntryLocalService(
		com.liferay.portlet.asset.service.AssetEntryLocalService assetEntryLocalService) {
		this.assetEntryLocalService = assetEntryLocalService;
	}

	/**
	 * Returns the asset entry remote service.
	 *
	 * @return the asset entry remote service
	 */
	public com.liferay.portlet.asset.service.AssetEntryService getAssetEntryService() {
		return assetEntryService;
	}

	/**
	 * Sets the asset entry remote service.
	 *
	 * @param assetEntryService the asset entry remote service
	 */
	public void setAssetEntryService(
		com.liferay.portlet.asset.service.AssetEntryService assetEntryService) {
		this.assetEntryService = assetEntryService;
	}

	/**
	 * Returns the asset entry persistence.
	 *
	 * @return the asset entry persistence
	 */
	public AssetEntryPersistence getAssetEntryPersistence() {
		return assetEntryPersistence;
	}

	/**
	 * Sets the asset entry persistence.
	 *
	 * @param assetEntryPersistence the asset entry persistence
	 */
	public void setAssetEntryPersistence(
		AssetEntryPersistence assetEntryPersistence) {
		this.assetEntryPersistence = assetEntryPersistence;
	}

	/**
	 * Returns the asset link local service.
	 *
	 * @return the asset link local service
	 */
	public com.liferay.portlet.asset.service.AssetLinkLocalService getAssetLinkLocalService() {
		return assetLinkLocalService;
	}

	/**
	 * Sets the asset link local service.
	 *
	 * @param assetLinkLocalService the asset link local service
	 */
	public void setAssetLinkLocalService(
		com.liferay.portlet.asset.service.AssetLinkLocalService assetLinkLocalService) {
		this.assetLinkLocalService = assetLinkLocalService;
	}

	/**
	 * Returns the asset link persistence.
	 *
	 * @return the asset link persistence
	 */
	public AssetLinkPersistence getAssetLinkPersistence() {
		return assetLinkPersistence;
	}

	/**
	 * Sets the asset link persistence.
	 *
	 * @param assetLinkPersistence the asset link persistence
	 */
	public void setAssetLinkPersistence(
		AssetLinkPersistence assetLinkPersistence) {
		this.assetLinkPersistence = assetLinkPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return Content.class;
	}

	protected String getModelClassName() {
		return Content.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = contentPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = org.kisti.edison.content.service.AdvancedContentLocalService.class)
	protected org.kisti.edison.content.service.AdvancedContentLocalService advancedContentLocalService;
	@BeanReference(type = org.kisti.edison.content.service.AdvancedContentService.class)
	protected org.kisti.edison.content.service.AdvancedContentService advancedContentService;
	@BeanReference(type = AdvancedContentPersistence.class)
	protected AdvancedContentPersistence advancedContentPersistence;
	@BeanReference(type = org.kisti.edison.content.service.ContentLocalService.class)
	protected org.kisti.edison.content.service.ContentLocalService contentLocalService;
	@BeanReference(type = org.kisti.edison.content.service.ContentService.class)
	protected org.kisti.edison.content.service.ContentService contentService;
	@BeanReference(type = ContentPersistence.class)
	protected ContentPersistence contentPersistence;
	@BeanReference(type = ContentFinder.class)
	protected ContentFinder contentFinder;
	@BeanReference(type = org.kisti.edison.content.service.GeneralContentLocalService.class)
	protected org.kisti.edison.content.service.GeneralContentLocalService generalContentLocalService;
	@BeanReference(type = org.kisti.edison.content.service.GeneralContentService.class)
	protected org.kisti.edison.content.service.GeneralContentService generalContentService;
	@BeanReference(type = GeneralContentPersistence.class)
	protected GeneralContentPersistence generalContentPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@BeanReference(type = com.liferay.portlet.asset.service.AssetEntryLocalService.class)
	protected com.liferay.portlet.asset.service.AssetEntryLocalService assetEntryLocalService;
	@BeanReference(type = com.liferay.portlet.asset.service.AssetEntryService.class)
	protected com.liferay.portlet.asset.service.AssetEntryService assetEntryService;
	@BeanReference(type = AssetEntryPersistence.class)
	protected AssetEntryPersistence assetEntryPersistence;
	@BeanReference(type = com.liferay.portlet.asset.service.AssetLinkLocalService.class)
	protected com.liferay.portlet.asset.service.AssetLinkLocalService assetLinkLocalService;
	@BeanReference(type = AssetLinkPersistence.class)
	protected AssetLinkPersistence assetLinkPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private ContentServiceClpInvoker _clpInvoker = new ContentServiceClpInvoker();
}