/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.kisti.edison.bestsimulation.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import org.kisti.edison.bestsimulation.service.persistence.ScienceAppExecutePK;

import java.io.Serializable;

/**
 * The base model interface for the ScienceAppExecute service. Represents a row in the &quot;EDSIM_ScienceAppExecute&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.kisti.edison.bestsimulation.model.impl.ScienceAppExecuteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.kisti.edison.bestsimulation.model.impl.ScienceAppExecuteImpl}.
 * </p>
 *
 * @author EDISON
 * @see ScienceAppExecute
 * @see org.kisti.edison.bestsimulation.model.impl.ScienceAppExecuteImpl
 * @see org.kisti.edison.bestsimulation.model.impl.ScienceAppExecuteModelImpl
 * @generated
 */
public interface ScienceAppExecuteModel extends BaseModel<ScienceAppExecute> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a science app execute model instance should use the {@link ScienceAppExecute} interface instead.
	 */

	/**
	 * Returns the primary key of this science app execute.
	 *
	 * @return the primary key of this science app execute
	 */
	public ScienceAppExecutePK getPrimaryKey();

	/**
	 * Sets the primary key of this science app execute.
	 *
	 * @param primaryKey the primary key of this science app execute
	 */
	public void setPrimaryKey(ScienceAppExecutePK primaryKey);

	/**
	 * Returns the execute date of this science app execute.
	 *
	 * @return the execute date of this science app execute
	 */
	@AutoEscape
	public String getExecuteDate();

	/**
	 * Sets the execute date of this science app execute.
	 *
	 * @param executeDate the execute date of this science app execute
	 */
	public void setExecuteDate(String executeDate);

	/**
	 * Returns the science app ID of this science app execute.
	 *
	 * @return the science app ID of this science app execute
	 */
	public long getScienceAppId();

	/**
	 * Sets the science app ID of this science app execute.
	 *
	 * @param scienceAppId the science app ID of this science app execute
	 */
	public void setScienceAppId(long scienceAppId);

	/**
	 * Returns the user cnt of this science app execute.
	 *
	 * @return the user cnt of this science app execute
	 */
	public long getUserCnt();

	/**
	 * Sets the user cnt of this science app execute.
	 *
	 * @param userCnt the user cnt of this science app execute
	 */
	public void setUserCnt(long userCnt);

	/**
	 * Returns the avg exe time of this science app execute.
	 *
	 * @return the avg exe time of this science app execute
	 */
	public long getAvgExeTime();

	/**
	 * Sets the avg exe time of this science app execute.
	 *
	 * @param avgExeTime the avg exe time of this science app execute
	 */
	public void setAvgExeTime(long avgExeTime);

	/**
	 * Returns the exe cnt of this science app execute.
	 *
	 * @return the exe cnt of this science app execute
	 */
	public long getExeCnt();

	/**
	 * Sets the exe cnt of this science app execute.
	 *
	 * @param exeCnt the exe cnt of this science app execute
	 */
	public void setExeCnt(long exeCnt);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.kisti.edison.bestsimulation.model.ScienceAppExecute scienceAppExecute);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.kisti.edison.bestsimulation.model.ScienceAppExecute> toCacheModel();

	@Override
	public org.kisti.edison.bestsimulation.model.ScienceAppExecute toEscapedModel();

	@Override
	public org.kisti.edison.bestsimulation.model.ScienceAppExecute toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}