/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.kisti.edison.bestsimulation.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import org.kisti.edison.bestsimulation.service.persistence.UniversityExecutePK;

import java.io.Serializable;

/**
 * The base model interface for the UniversityExecute service. Represents a row in the &quot;EDSIM_UniversityExecute&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.kisti.edison.bestsimulation.model.impl.UniversityExecuteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.kisti.edison.bestsimulation.model.impl.UniversityExecuteImpl}.
 * </p>
 *
 * @author EDISON
 * @see UniversityExecute
 * @see org.kisti.edison.bestsimulation.model.impl.UniversityExecuteImpl
 * @see org.kisti.edison.bestsimulation.model.impl.UniversityExecuteModelImpl
 * @generated
 */
public interface UniversityExecuteModel extends BaseModel<UniversityExecute> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a university execute model instance should use the {@link UniversityExecute} interface instead.
	 */

	/**
	 * Returns the primary key of this university execute.
	 *
	 * @return the primary key of this university execute
	 */
	public UniversityExecutePK getPrimaryKey();

	/**
	 * Sets the primary key of this university execute.
	 *
	 * @param primaryKey the primary key of this university execute
	 */
	public void setPrimaryKey(UniversityExecutePK primaryKey);

	/**
	 * Returns the execute date of this university execute.
	 *
	 * @return the execute date of this university execute
	 */
	@AutoEscape
	public String getExecuteDate();

	/**
	 * Sets the execute date of this university execute.
	 *
	 * @param executeDate the execute date of this university execute
	 */
	public void setExecuteDate(String executeDate);

	/**
	 * Returns the university field of this university execute.
	 *
	 * @return the university field of this university execute
	 */
	public long getUniversityField();

	/**
	 * Sets the university field of this university execute.
	 *
	 * @param universityField the university field of this university execute
	 */
	public void setUniversityField(long universityField);

	/**
	 * Returns the user cnt of this university execute.
	 *
	 * @return the user cnt of this university execute
	 */
	public long getUserCnt();

	/**
	 * Sets the user cnt of this university execute.
	 *
	 * @param userCnt the user cnt of this university execute
	 */
	public void setUserCnt(long userCnt);

	/**
	 * Returns the avg exe time of this university execute.
	 *
	 * @return the avg exe time of this university execute
	 */
	public long getAvgExeTime();

	/**
	 * Sets the avg exe time of this university execute.
	 *
	 * @param avgExeTime the avg exe time of this university execute
	 */
	public void setAvgExeTime(long avgExeTime);

	/**
	 * Returns the exe cnt of this university execute.
	 *
	 * @return the exe cnt of this university execute
	 */
	public long getExeCnt();

	/**
	 * Sets the exe cnt of this university execute.
	 *
	 * @param exeCnt the exe cnt of this university execute
	 */
	public void setExeCnt(long exeCnt);

	/**
	 * Returns the cpu time of this university execute.
	 *
	 * @return the cpu time of this university execute
	 */
	public long getCpuTime();

	/**
	 * Sets the cpu time of this university execute.
	 *
	 * @param cpuTime the cpu time of this university execute
	 */
	public void setCpuTime(long cpuTime);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.kisti.edison.bestsimulation.model.UniversityExecute universityExecute);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.kisti.edison.bestsimulation.model.UniversityExecute> toCacheModel();

	@Override
	public org.kisti.edison.bestsimulation.model.UniversityExecute toEscapedModel();

	@Override
	public org.kisti.edison.bestsimulation.model.UniversityExecute toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}