/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.kisti.edison.bestsimulation.model;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import org.kisti.edison.bestsimulation.service.persistence.VirtualLabClassStatisticsPK;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the VirtualLabClassStatistics service. Represents a row in the &quot;EDSIM_VirtualLabClassStatistics&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.kisti.edison.bestsimulation.model.impl.VirtualLabClassStatisticsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.kisti.edison.bestsimulation.model.impl.VirtualLabClassStatisticsImpl}.
 * </p>
 *
 * @author EDISON
 * @see VirtualLabClassStatistics
 * @see org.kisti.edison.bestsimulation.model.impl.VirtualLabClassStatisticsImpl
 * @see org.kisti.edison.bestsimulation.model.impl.VirtualLabClassStatisticsModelImpl
 * @generated
 */
public interface VirtualLabClassStatisticsModel extends BaseModel<VirtualLabClassStatistics> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a virtual lab class statistics model instance should use the {@link VirtualLabClassStatistics} interface instead.
	 */

	/**
	 * Returns the primary key of this virtual lab class statistics.
	 *
	 * @return the primary key of this virtual lab class statistics
	 */
	public VirtualLabClassStatisticsPK getPrimaryKey();

	/**
	 * Sets the primary key of this virtual lab class statistics.
	 *
	 * @param primaryKey the primary key of this virtual lab class statistics
	 */
	public void setPrimaryKey(VirtualLabClassStatisticsPK primaryKey);

	/**
	 * Returns the virtual lab ID of this virtual lab class statistics.
	 *
	 * @return the virtual lab ID of this virtual lab class statistics
	 */
	public long getVirtualLabId();

	/**
	 * Sets the virtual lab ID of this virtual lab class statistics.
	 *
	 * @param virtualLabId the virtual lab ID of this virtual lab class statistics
	 */
	public void setVirtualLabId(long virtualLabId);

	/**
	 * Returns the class ID of this virtual lab class statistics.
	 *
	 * @return the class ID of this virtual lab class statistics
	 */
	@AutoEscape
	public String getClassId();

	/**
	 * Sets the class ID of this virtual lab class statistics.
	 *
	 * @param classId the class ID of this virtual lab class statistics
	 */
	public void setClassId(String classId);

	/**
	 * Returns the virtual lab title of this virtual lab class statistics.
	 *
	 * @return the virtual lab title of this virtual lab class statistics
	 */
	public String getVirtualLabTitle();

	/**
	 * Returns the localized virtual lab title of this virtual lab class statistics in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized virtual lab title of this virtual lab class statistics
	 */
	@AutoEscape
	public String getVirtualLabTitle(Locale locale);

	/**
	 * Returns the localized virtual lab title of this virtual lab class statistics in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized virtual lab title of this virtual lab class statistics. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getVirtualLabTitle(Locale locale, boolean useDefault);

	/**
	 * Returns the localized virtual lab title of this virtual lab class statistics in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized virtual lab title of this virtual lab class statistics
	 */
	@AutoEscape
	public String getVirtualLabTitle(String languageId);

	/**
	 * Returns the localized virtual lab title of this virtual lab class statistics in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized virtual lab title of this virtual lab class statistics
	 */
	@AutoEscape
	public String getVirtualLabTitle(String languageId, boolean useDefault);

	@AutoEscape
	public String getVirtualLabTitleCurrentLanguageId();

	@AutoEscape
	public String getVirtualLabTitleCurrentValue();

	/**
	 * Returns a map of the locales and localized virtual lab titles of this virtual lab class statistics.
	 *
	 * @return the locales and localized virtual lab titles of this virtual lab class statistics
	 */
	public Map<Locale, String> getVirtualLabTitleMap();

	/**
	 * Sets the virtual lab title of this virtual lab class statistics.
	 *
	 * @param virtualLabTitle the virtual lab title of this virtual lab class statistics
	 */
	public void setVirtualLabTitle(String virtualLabTitle);

	/**
	 * Sets the localized virtual lab title of this virtual lab class statistics in the language.
	 *
	 * @param virtualLabTitle the localized virtual lab title of this virtual lab class statistics
	 * @param locale the locale of the language
	 */
	public void setVirtualLabTitle(String virtualLabTitle, Locale locale);

	/**
	 * Sets the localized virtual lab title of this virtual lab class statistics in the language, and sets the default locale.
	 *
	 * @param virtualLabTitle the localized virtual lab title of this virtual lab class statistics
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setVirtualLabTitle(String virtualLabTitle, Locale locale,
		Locale defaultLocale);

	public void setVirtualLabTitleCurrentLanguageId(String languageId);

	/**
	 * Sets the localized virtual lab titles of this virtual lab class statistics from the map of locales and localized virtual lab titles.
	 *
	 * @param virtualLabTitleMap the locales and localized virtual lab titles of this virtual lab class statistics
	 */
	public void setVirtualLabTitleMap(Map<Locale, String> virtualLabTitleMap);

	/**
	 * Sets the localized virtual lab titles of this virtual lab class statistics from the map of locales and localized virtual lab titles, and sets the default locale.
	 *
	 * @param virtualLabTitleMap the locales and localized virtual lab titles of this virtual lab class statistics
	 * @param defaultLocale the default locale
	 */
	public void setVirtualLabTitleMap(Map<Locale, String> virtualLabTitleMap,
		Locale defaultLocale);

	/**
	 * Returns the class title of this virtual lab class statistics.
	 *
	 * @return the class title of this virtual lab class statistics
	 */
	public String getClassTitle();

	/**
	 * Returns the localized class title of this virtual lab class statistics in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized class title of this virtual lab class statistics
	 */
	@AutoEscape
	public String getClassTitle(Locale locale);

	/**
	 * Returns the localized class title of this virtual lab class statistics in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized class title of this virtual lab class statistics. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getClassTitle(Locale locale, boolean useDefault);

	/**
	 * Returns the localized class title of this virtual lab class statistics in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized class title of this virtual lab class statistics
	 */
	@AutoEscape
	public String getClassTitle(String languageId);

	/**
	 * Returns the localized class title of this virtual lab class statistics in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized class title of this virtual lab class statistics
	 */
	@AutoEscape
	public String getClassTitle(String languageId, boolean useDefault);

	@AutoEscape
	public String getClassTitleCurrentLanguageId();

	@AutoEscape
	public String getClassTitleCurrentValue();

	/**
	 * Returns a map of the locales and localized class titles of this virtual lab class statistics.
	 *
	 * @return the locales and localized class titles of this virtual lab class statistics
	 */
	public Map<Locale, String> getClassTitleMap();

	/**
	 * Sets the class title of this virtual lab class statistics.
	 *
	 * @param classTitle the class title of this virtual lab class statistics
	 */
	public void setClassTitle(String classTitle);

	/**
	 * Sets the localized class title of this virtual lab class statistics in the language.
	 *
	 * @param classTitle the localized class title of this virtual lab class statistics
	 * @param locale the locale of the language
	 */
	public void setClassTitle(String classTitle, Locale locale);

	/**
	 * Sets the localized class title of this virtual lab class statistics in the language, and sets the default locale.
	 *
	 * @param classTitle the localized class title of this virtual lab class statistics
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setClassTitle(String classTitle, Locale locale,
		Locale defaultLocale);

	public void setClassTitleCurrentLanguageId(String languageId);

	/**
	 * Sets the localized class titles of this virtual lab class statistics from the map of locales and localized class titles.
	 *
	 * @param classTitleMap the locales and localized class titles of this virtual lab class statistics
	 */
	public void setClassTitleMap(Map<Locale, String> classTitleMap);

	/**
	 * Sets the localized class titles of this virtual lab class statistics from the map of locales and localized class titles, and sets the default locale.
	 *
	 * @param classTitleMap the locales and localized class titles of this virtual lab class statistics
	 * @param defaultLocale the default locale
	 */
	public void setClassTitleMap(Map<Locale, String> classTitleMap,
		Locale defaultLocale);

	/**
	 * Returns the virtual lab person name of this virtual lab class statistics.
	 *
	 * @return the virtual lab person name of this virtual lab class statistics
	 */
	@AutoEscape
	public String getVirtualLabPersonName();

	/**
	 * Sets the virtual lab person name of this virtual lab class statistics.
	 *
	 * @param virtualLabPersonName the virtual lab person name of this virtual lab class statistics
	 */
	public void setVirtualLabPersonName(String virtualLabPersonName);

	/**
	 * Returns the register student cnt of this virtual lab class statistics.
	 *
	 * @return the register student cnt of this virtual lab class statistics
	 */
	public long getRegisterStudentCnt();

	/**
	 * Sets the register student cnt of this virtual lab class statistics.
	 *
	 * @param registerStudentCnt the register student cnt of this virtual lab class statistics
	 */
	public void setRegisterStudentCnt(long registerStudentCnt);

	/**
	 * Returns the virtual lab users ID of this virtual lab class statistics.
	 *
	 * @return the virtual lab users ID of this virtual lab class statistics
	 */
	@AutoEscape
	public String getVirtualLabUsersId();

	/**
	 * Sets the virtual lab users ID of this virtual lab class statistics.
	 *
	 * @param virtualLabUsersId the virtual lab users ID of this virtual lab class statistics
	 */
	public void setVirtualLabUsersId(String virtualLabUsersId);

	/**
	 * Returns the science app ID of this virtual lab class statistics.
	 *
	 * @return the science app ID of this virtual lab class statistics
	 */
	@AutoEscape
	public String getScienceAppId();

	/**
	 * Sets the science app ID of this virtual lab class statistics.
	 *
	 * @param scienceAppId the science app ID of this virtual lab class statistics
	 */
	public void setScienceAppId(String scienceAppId);

	/**
	 * Returns the execute user cnt of this virtual lab class statistics.
	 *
	 * @return the execute user cnt of this virtual lab class statistics
	 */
	public long getExecuteUserCnt();

	/**
	 * Sets the execute user cnt of this virtual lab class statistics.
	 *
	 * @param executeUserCnt the execute user cnt of this virtual lab class statistics
	 */
	public void setExecuteUserCnt(long executeUserCnt);

	/**
	 * Returns the execute cnt of this virtual lab class statistics.
	 *
	 * @return the execute cnt of this virtual lab class statistics
	 */
	public long getExecuteCnt();

	/**
	 * Sets the execute cnt of this virtual lab class statistics.
	 *
	 * @param executeCnt the execute cnt of this virtual lab class statistics
	 */
	public void setExecuteCnt(long executeCnt);

	/**
	 * Returns the cputime of this virtual lab class statistics.
	 *
	 * @return the cputime of this virtual lab class statistics
	 */
	@AutoEscape
	public String getCputime();

	/**
	 * Sets the cputime of this virtual lab class statistics.
	 *
	 * @param cputime the cputime of this virtual lab class statistics
	 */
	public void setCputime(String cputime);

	/**
	 * Returns the group ID of this virtual lab class statistics.
	 *
	 * @return the group ID of this virtual lab class statistics
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this virtual lab class statistics.
	 *
	 * @param groupId the group ID of this virtual lab class statistics
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the university of this virtual lab class statistics.
	 *
	 * @return the university of this virtual lab class statistics
	 */
	public long getUniversity();

	/**
	 * Sets the university of this virtual lab class statistics.
	 *
	 * @param university the university of this virtual lab class statistics
	 */
	public void setUniversity(long university);

	/**
	 * Returns the class create dt of this virtual lab class statistics.
	 *
	 * @return the class create dt of this virtual lab class statistics
	 */
	public Date getClassCreateDt();

	/**
	 * Sets the class create dt of this virtual lab class statistics.
	 *
	 * @param classCreateDt the class create dt of this virtual lab class statistics
	 */
	public void setClassCreateDt(Date classCreateDt);

	/**
	 * Returns the virtual lab use yn of this virtual lab class statistics.
	 *
	 * @return the virtual lab use yn of this virtual lab class statistics
	 */
	@AutoEscape
	public String getVirtualLabUseYn();

	/**
	 * Sets the virtual lab use yn of this virtual lab class statistics.
	 *
	 * @param virtualLabUseYn the virtual lab use yn of this virtual lab class statistics
	 */
	public void setVirtualLabUseYn(String virtualLabUseYn);

	/**
	 * Returns the class use yn of this virtual lab class statistics.
	 *
	 * @return the class use yn of this virtual lab class statistics
	 */
	@AutoEscape
	public String getClassUseYn();

	/**
	 * Sets the class use yn of this virtual lab class statistics.
	 *
	 * @param classUseYn the class use yn of this virtual lab class statistics
	 */
	public void setClassUseYn(String classUseYn);

	/**
	 * Returns the last modified dt of this virtual lab class statistics.
	 *
	 * @return the last modified dt of this virtual lab class statistics
	 */
	public Date getLastModifiedDt();

	/**
	 * Sets the last modified dt of this virtual lab class statistics.
	 *
	 * @param lastModifiedDt the last modified dt of this virtual lab class statistics
	 */
	public void setLastModifiedDt(Date lastModifiedDt);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public String[] getAvailableLanguageIds();

	public String getDefaultLanguageId();

	public void prepareLocalizedFieldsForImport() throws LocaleException;

	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.kisti.edison.bestsimulation.model.VirtualLabClassStatistics virtualLabClassStatistics);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.kisti.edison.bestsimulation.model.VirtualLabClassStatistics> toCacheModel();

	@Override
	public org.kisti.edison.bestsimulation.model.VirtualLabClassStatistics toEscapedModel();

	@Override
	public org.kisti.edison.bestsimulation.model.VirtualLabClassStatistics toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}