/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.kisti.edison.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import org.kisti.edison.service.persistence.RequestMemberPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the RequestMember service. Represents a row in the &quot;EDSIMPRO_RequestMember&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.kisti.edison.model.impl.RequestMemberModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.kisti.edison.model.impl.RequestMemberImpl}.
 * </p>
 *
 * @author edison
 * @see RequestMember
 * @see org.kisti.edison.model.impl.RequestMemberImpl
 * @see org.kisti.edison.model.impl.RequestMemberModelImpl
 * @generated
 */
public interface RequestMemberModel extends BaseModel<RequestMember> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a request member model instance should use the {@link RequestMember} interface instead.
	 */

	/**
	 * Returns the primary key of this request member.
	 *
	 * @return the primary key of this request member
	 */
	public RequestMemberPK getPrimaryKey();

	/**
	 * Sets the primary key of this request member.
	 *
	 * @param primaryKey the primary key of this request member
	 */
	public void setPrimaryKey(RequestMemberPK primaryKey);

	/**
	 * Returns the request seq of this request member.
	 *
	 * @return the request seq of this request member
	 */
	public long getRequestSeq();

	/**
	 * Sets the request seq of this request member.
	 *
	 * @param requestSeq the request seq of this request member
	 */
	public void setRequestSeq(long requestSeq);

	/**
	 * Returns the simulation project ID of this request member.
	 *
	 * @return the simulation project ID of this request member
	 */
	public long getSimulationProjectId();

	/**
	 * Sets the simulation project ID of this request member.
	 *
	 * @param simulationProjectId the simulation project ID of this request member
	 */
	public void setSimulationProjectId(long simulationProjectId);

	/**
	 * Returns the user ID of this request member.
	 *
	 * @return the user ID of this request member
	 */
	public Long getUserId();

	/**
	 * Sets the user ID of this request member.
	 *
	 * @param userId the user ID of this request member
	 */
	public void setUserId(Long userId);

	/**
	 * Returns the request date of this request member.
	 *
	 * @return the request date of this request member
	 */
	public Date getRequestDate();

	/**
	 * Sets the request date of this request member.
	 *
	 * @param requestDate the request date of this request member
	 */
	public void setRequestDate(Date requestDate);

	/**
	 * Returns the process date of this request member.
	 *
	 * @return the process date of this request member
	 */
	public Date getProcessDate();

	/**
	 * Sets the process date of this request member.
	 *
	 * @param processDate the process date of this request member
	 */
	public void setProcessDate(Date processDate);

	/**
	 * Returns the request state of this request member.
	 *
	 * @return the request state of this request member
	 */
	@AutoEscape
	public String getRequestState();

	/**
	 * Sets the request state of this request member.
	 *
	 * @param requestState the request state of this request member
	 */
	public void setRequestState(String requestState);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.kisti.edison.model.RequestMember requestMember);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.kisti.edison.model.RequestMember> toCacheModel();

	@Override
	public org.kisti.edison.model.RequestMember toEscapedModel();

	@Override
	public org.kisti.edison.model.RequestMember toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}